<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Fri, 24 Apr 2020 21:15:35 +0000
// --------------------------------------------------------------------------------

$l['archive_fullversion'] = 'Tam Versiyon:';
$l['archive_replies'] = 'Yorumlar';
$l['archive_reply'] = 'Yorum';
$l['archive_pages'] = 'Sayfalar:';
$l['archive_note'] = 'Şu anda <strong>arşiv</strong> modunu görüntülemektesiniz. <a href="{1}">Tam versiyonu görüntülemek için buraya</a> tıklayınız.';
$l['archive_nopermission'] = 'Üzgünüz, bu kaynağa erişim yetkiniz bulunmuyor.';
$l['error_nothreads'] = 'Şu anda bu forumda konu bulunmuyor veya silinmiş olabilir.';
$l['error_nopermission'] = 'Bu forumdaki konuları görüntüleyebilmek için yetkiniz bulunmuyor.';
$l['error_unapproved_thread'] = 'Bu konu onaylanmamış. Lütfen, bu konuyu <a href="{1}">tam versiyon</a> kısmından görüntüleyiniz.';
$l['archive_not_found'] = 'Belirttiğiniz sayfa veya konu bu forumda bulunamadı.';
$l['error_mustlogin'] = 'Bu foruma erişebilmeniz için giriş yapmanız gerekiyor. ';
