<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Wed, 06 May 2020 06:29:35 +0000
// --------------------------------------------------------------------------------

$l['nav_calendar'] = 'Takvim';
$l['nav_viewevent'] = 'Etkinlikleri Göster';
$l['nav_dayview'] = 'Günlük Gösterim';
$l['nav_addevent'] = 'Etkinlik Ekle';
$l['nav_editevent'] = 'Etkinlik Düzenle';
$l['nav_move_event'] = 'Etkinliği Taşı';
$l['calendar_disabled'] = 'Takvimin işlevselliği forum yönetimi tarafından kullanıma kapatılmıştır.';
$l['alt_month_1'] = 'Ocak';
$l['alt_month_2'] = 'Şubat';
$l['alt_month_3'] = 'Mart';
$l['alt_month_4'] = 'Nisan';
$l['alt_month_5'] = 'Mayıs';
$l['alt_month_6'] = 'Haziran';
$l['alt_month_7'] = 'Temmuz';
$l['alt_month_8'] = 'Ağustos';
$l['alt_month_9'] = 'Eylül';
$l['alt_month_10'] = 'Ekim';
$l['alt_month_11'] = 'Kasım';
$l['alt_month_12'] = 'Aralık';
$l['add_private_event'] = 'Özel Etkinlik Ekle';
$l['add_public_event'] = 'Genel Etkinlik Ekle';
$l['calendar'] = 'Takvim';
$l['jump_month'] = 'Ay / Yıl Seç';
$l['birthdays_on_day'] = '{1} Tarihinde Doğanlar';
$l['birthdayhidden'] = 'Gizli';
$l['event'] = 'etkinlik';
$l['events'] = 'etkinlikler';
$l['add_event'] = 'Etkinlik Ekle';
$l['event_date'] = 'Etkinlik Tarihi:';
$l['event_recurring_start_date'] = 'Başlangıç Tarihi:';
$l['event_recurring_end_date'] = 'Bitiş Tarihi:';
$l['event_recurring_repeat_days'] = 'Etkinlik Günü Tekrarlama:';
$l['event_name'] = 'Etkinlik Başlığı:';
$l['event_details'] = 'Etkinlik Detayları:';
$l['event_options'] = 'Seçenekler:';
$l['private_option'] = '<b>Özel</b> Bu etkinliği sadece bu foruma kayıtlı kullanıcılar görebilsin.';
$l['delete_option'] = '<b>Sil:</b> Bu etkinliği sil.';
$l['post_event'] = 'Etkinliği Gönder';
$l['day_view'] = 'Günlük Gösterim';
$l['birthday'] = 'Doğum Günü';
$l['birthdays'] = 'Doğum Günleri';
$l['event_author'] = 'Etkinlik Sahibi:';
$l['edit_event'] = 'Etkinliği Düzenle';
$l['view_event'] = 'Etkinliği Görüntüle';
$l['no_events'] = 'Bugüne ait etkinlik kaydı bulunamadı. <a href="calendar.php?action=addevent&amp;calendar={1}&amp;day={2}&amp;month={3}&amp;year={4}">Bugüne etkinlik ekle!</a>';
$l['years_old'] = '{1} Yaşında';
$l['alt_edit'] = 'Bu Etkinliği Düzenle';
$l['alt_delete'] = 'Bu Etkinliği Sil';
$l['moderator_options'] = 'Yönetici Ayarları';
$l['approve_event'] = 'Bu Etkinliği Onayla';
$l['unapprove_event'] = 'Bu Etkinliği Onaylama (İptal)';
$l['move_event'] = 'Etkinliği Taşı';
$l['repeats_every_day'] = 'Günlük Tekrarlananlar';
$l['repeats_every_x_days'] = '{1} Günde Birkez Tekrarlananlar';
$l['repeats_on_weekdays'] = 'Pazartesi ve Cuma Günleri Arası Tekrarlananlar';
$l['every_week_on_days'] = '{1} Haftada Birkez Tekrarlananlar';
$l['every_week'] = 'Her Hafta Tekrarlananlar';
$l['every_x_weeks_on_days'] = 'Her {1} Hafta ile <br />{2} Tekrarlananlar';
$l['every_x_weeks'] = 'Her {1} Haftada Bir Tekrarlananlar';
$l['every_month_on_day'] = 'Her Ayın {1}<br />Gününde Tekrarlananlar';
$l['every_x_months_on_day'] = 'Her Ayın {2}<br />{1} Gününde Tekrarlananlar';
$l['every_month_on_weekday'] = 'Her Ayın {2} {1}<br /> Gününde tekrarlanacaktır';
$l['every_x_months_on_weekday'] = 'Her {3} ayda bir {2} {1}<br /> Tarihinde tekrarlanacaktır.';
$l['weekday_occurance_1'] = 'İlk';
$l['weekday_occurance_2'] = 'İkinci';
$l['weekday_occurance_3'] = 'Üçüncü';
$l['weekday_occurance_4'] = 'Dürdüncü';
$l['weekday_occurance_last'] = 'Son';
$l['every_year_on_day'] = 'Her Yıl {1} {2} Tekrarlanan';
$l['every_x_years_on_day'] = 'Her {3} Yıl ile {1} {2} Tekrarlanan';
$l['every_year_on_weekday'] = 'Her {1} {2} Yıl {3} Tekrarlananlar';
$l['every_x_year_on_weekday'] = '{1} {2}  {3}  {4}';
$l['delete_event'] = 'Bu Etkinliği Sil';
$l['delete_q'] = 'Onay?';
$l['delete_1'] = 'Bu etkinliği silmek istiyorsanız, sol taraftaki onay kutusunu işaretleyip sağdaki sil butonuna tıklayınız.';
$l['delete_2'] = '<b>Uyarı:</b> Bu işlem geri alınamaz!';
$l['delete_now'] = 'Sil';
$l['delete_no_checkbox'] = '"SİL" onay kutusu işaretli olmadığı için etkinlik silinmedi.';
$l['jump_to_calendar'] = 'Takvim Seçimi:';
$l['select_calendar'] = 'Takvim:';
$l['type_single'] = 'Tek Günlük/Geçici Etkinlik';
$l['type_ranged'] = 'Aralıklı veya devamlı/Gelişmiş Etkinlik Seçeneklerini Göster';
$l['enter_time'] = 'Saat:';
$l['start_time'] = 'Başlangıç Tarihi:';
$l['end_time'] = 'Bitiş Tarihi:';
$l['timezone'] = 'Zaman Dilimi:';
$l['ignore_timezone'] = '<strong>Saat Dilimini Yoksay:</strong> (Saat dilimini kullanmanız önerilir!)';
$l['repeats'] = 'Tekrarlama:';
$l['does_not_repeat'] = 'Tekrar Etme';
$l['repeats_daily'] = 'Günlük Tekrarla';
$l['repeats_weekdays'] = 'Hafta içi her gün (Pazartesi-Cuma)';
$l['repeats_weekly'] = 'Haftalık Tekrarla';
$l['repeats_every'] = 'Her Zaman Tekrarla';
$l['day_or_days'] = 'Gün';
$l['week_or_weeks_on'] = 'Hafta';
$l['repeats_monthly'] = 'Aylık Tekrarla';
$l['repeats_yearly'] = 'Yıllık Tekrarla';
$l['repeats_on_day'] = 'Her Gün Tekrarla';
$l['of_every'] = 'Her';
$l['month_or_months'] = 'AY';
$l['repeats_on_the'] = 'Üzerinden tekrarla';
$l['day_of_every'] = 'Her Gün';
$l['repeats_on'] = 'Tekrarla';
$l['every'] = 'Her';
$l['year_or_years'] = 'Yıl';
$l['of'] = '';
$l['move_to_calendar'] = 'Takvime Taşı';
$l['weekly_overview'] = 'Haftalık Genel Bakış';
$l['previous_week'] = 'Önceki Hafta';
$l['next_week'] = 'Sonraki Hafta';
$l['first'] = 'İlk';
$l['second'] = 'İkinci';
$l['third'] = 'Üçüncü';
$l['fourth'] = 'Dürdüncü';
$l['last'] = 'Son';
$l['all_day'] = 'Bütün Günler';
$l['starts'] = 'Başlangıç: ';
$l['finishes'] = 'Bitiş: ';
$l['error_incorrectday'] = 'Geçersiz bir gün seçtiniz. Lütfen geri dönüp tekrar deneyiniz.';
$l['error_invalidevent'] = 'Belirttiğiniz etkinlik ya geçersiz ya da mevcut değil.';
$l['invalid_calendar'] = 'Belirtmiş olduğunuz takvim bulunamıyor. Doğru işlem yaptığınızdan emin misiniz?';
$l['redirect_eventdeleted'] = 'Etkinlikler başarılı olarak silinmiştir.<br />Şimdi takvim sayfasına geri yönlendiriliyorsunuz...';
$l['redirect_eventupdated'] = 'Etkinlik başarılı olarak güncellendi.';
$l['redirect_eventadded'] = 'Etkinlik başarılı olarak oluşturuldu.';
$l['redirect_eventadded_moderation'] = 'Etkinlik başarıyla oluşturuldu fakat yönetici tarafından onay beklemektedir.<br />Şimdi takvim sayfasına geri yönlendiriliyorsunuz...';
$l['redirect_eventunapproved'] = 'Etkinliğin onayı başarılı olarak kaldırıldı.';
$l['redirect_eventapproved'] = 'Etkinlik başarılı olarak onaylandı.';
$l['redirect_eventmoved'] = 'Etkinlik başarıyla taşınmıştır.';
