<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Fri, 24 Apr 2020 21:20:31 +0000
// --------------------------------------------------------------------------------

$l['contact'] = 'İletişim Formu';
$l['contact_no_message'] = 'Gönderilecek bir mesaj girmediniz. Lütfen kısa ve açıklayıcı bir mesaj giriniz.';
$l['contact_no_subject'] = 'Mesaj başlığı girmediniz. Lütfen bir başlık giriniz.';
$l['contact_no_email'] = 'E-posta adresiniz geçerli değil. Lütfen geçerli bir e-posta adresi giriniz.';
$l['contact_success_message'] = 'Teşekkürler. Mesajınız başarıyla yöneticiye gönderildi.';
$l['contact_subject'] = 'Başlık';
$l['contact_subject_desc'] = 'Lütfen iletişim için bir başlık giriniz.';
$l['contact_message'] = 'Mesajınız';
$l['contact_message_desc'] = 'Göndermek istediğiniz mesaj hakkında detayları bu alana giriniz.';
$l['contact_email'] = 'E-posta Adresiniz';
$l['contact_email_desc'] = 'Geri dönüş için irtibat kurulmasını istediğiniz e-posta adresinizi giriniz.';
$l['contact_send'] = 'Gönder';
$l['subject_too_long'] = 'Mesaj başlığı çok uzun. Lütfen <b>{1}</b> karakterden daha kısa bir başlık giriniz. (Şu anda girilen karakter sayısı: <b>{2}</b>) .';
$l['message_too_short'] = 'Mesaj içeriği ya çok kısa ya da henüz hiçbir şey yazmadınız. Lütfen <b>{1}</b> karakterden daha uzun bir içerik giriniz. (Şu anda girilen karakter sayısı: <b>{2}</b>)';
$l['message_too_long'] = 'Mesaj içeriği çok uzun. Lütfen <b>{1}</b> karakterden daha kısa bir içerik giriniz. (Şu anda girilen karakter sayısı: <b>{2}</b>)';
$l['error_stop_forum_spam_spammer'] = 'Üzgünüz, {1} bilinen bir spam ile eşleştiği tespit edildi. Bu nedenle iletişim formu ile mesaj gönderiminiz bloke edilmiştir.';
$l['error_stop_forum_spam_fetching'] = 'Üzgünüz, spam doğrulaması için veritabanı ile bağlantı kurulamadığından dolayı mesajınız gönderilemedi. Lütfen daha sonra tekrar deneyiniz.';
