<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Fri, 24 Apr 2020 21:27:13 +0000
// --------------------------------------------------------------------------------

$l['pmdata_too_long_subject'] = 'Özel mesaj başlığı çok uzun. Lütfen daha kısa bir başlık giriniz.';
$l['pmdata_code_no_subject'] = '[Başlıksız]';
$l['pmdata_missing_subject'] = 'Mesajınız için bir başlık girmediniz. Lütfen kısa bir başlık giriniz.';
$l['pmdata_missing_message'] = 'Gönderilecek bir mesaj içeriği girmediniz. Lütfen kısa ve açıklayıcı bir mesaj içeriği girin.';
$l['pmdata_message_too_long'] = 'Mesajınız çok uzun. Lütfen, {1} karakterden daha kısa bir mesaj giriniz. Şuanki karakter sayısı {2}\'dir.';
$l['pmdata_invalid_recipients'] = 'Göndermek için belirtmiş olduğunuz kullanıcı/üye sitemizde mevcut değil. <b>Geçersiz Kullanıcılar:</b> {1}';
$l['pmdata_no_recipients'] = 'Mesajı göndermek için herhangi bir kullanıcı/üye belirtmediniz. Mesajı göndermek için en az bir kullanıcı (alıcı) adı belirtmelisiniz.';
$l['pmdata_too_many_recipients'] = 'Bir mesajı en fazla bir seferde {1} kişiye gönderebilme izniniz var.';
$l['pmdata_recipient_is_ignoring'] = 'Özel mesajı göndermek istediğiniz, {1} isimli kullanıcı sizi engellemiş. Mesajınız gönderilemiyor.';
$l['pmdata_recipient_has_buddy_only'] = '{1} isimli kullanıcının arkadaş listesinde ekli olmadığınız için özel mesaj gönderemezsiniz.';
$l['pmdata_recipient_pms_disabled'] = '{1} isimli kullanıcı özel mesaj almayı kapatmış. Bu nedenle özel mesaj gönderemezsiniz.';
$l['pmdata_recipient_reached_quota'] = '{1} isimli kullanıcının özel mesaj kotası dolu olduğu için mesajınız gönderilemiyor.';
$l['pmdata_pm_flooding'] = 'Flood mesaj koruması: Art arda bu kadar hızlı mesaj gönderemezsiniz. Tekrar mesaj gönderebilmek için lütfen {1} saniye daha bekleyiniz.';
$l['pmdata_pm_flooding_one_second'] = 'Flood mesaj koruması: Art arda bu kadar hızlı mesaj gönderemezsiniz. Tekrar mesaj gönderebilmek için lütfen birkaç saniye daha bekleyiniz.';
