<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Fri, 24 Apr 2020 21:33:47 +0000
// --------------------------------------------------------------------------------

$l['userdata_missing_username'] = 'Kullanıcı adı girmediniz. Lütfen bir kullanıcı adı giriniz.';
$l['userdata_banned_username'] = 'Girmiş olduğunuz kullanıcı adı mevcut değil veya engellenmiş olabilir. Lütfen farklı bir kullanıcı adı giriniz.';
$l['userdata_bad_characters_username'] = 'Girmiş olduğunuz kullanıcı adı kötü veya engelli karakterler içeriyor. Lütfen farklı bir kullanıcı adı giriniz.';
$l['userdata_invalid_username_length'] = 'Girmiş olduğunuz kullanıcı adı geçersiz uzunlukta. Lütfen {1} ile {2} karakter uzunluğunda bir kullanıcı adı giriniz.';
$l['userdata_invalid_usertitle_length'] = 'Özel kullanıcı başlığı geçersiz uzunlukta. Lütfen {1} karakterden daha kısa bir başlık giriniz.';
$l['userdata_username_exists'] = 'Girdiğiniz kullanıcı adı sistemimizde mevcut yada engellenmiş olabilir. Lütfen farklı bir kullanıcı adı deneyiniz.';
$l['userdata_invalid_password_length'] = 'Girmiş olduğunuz şifre geçersiz uzunlukta. Lütfen {1} ile {2} karakter uzunluğunda bir şifre giriniz.';
$l['userdata_no_complex_characters'] = 'Girdiğiniz şifre yeterince karmaşık değil. En az {1} karakter uzunluğunda ve en az bir büyük harf, bir küçük harf ve bir de rakam içeren bir şifre giriniz.';
$l['userdata_passwords_dont_match'] = 'Girmiş olduğunuz şifreler uyuşmuyor. Lütfen şifrenizin doğruluğunu kontrol ediniz.';
$l['userdata_bad_password_security'] = 'Girdiğiniz parola, kullanıcı adı veya e-posta adresi ile aynı görülüyor, lütfen daha güçlü bir parola giriniz.';
$l['userdata_missing_email'] = 'E-posta adresi girmediniz. Lütfen bir e-posta adresi giriniz.';
$l['userdata_invalid_email_format'] = 'Girmiş olduğunuz e-posta adresi geçersiz. Lütfen geçerli bir e-posta adresi giriniz.';
$l['userdata_emails_dont_match'] = 'Girmiş olduğunuz e-posta adresleri uyuşmuyor. Lütfen e-posta adresinizin doğruluğunu kontrol ediniz.';
$l['userdata_banned_email'] = 'Girmiş olduğunuz e-posta adresinin kullanımı engellenmiş. Lütfen farklı bir e-posta adresi giriniz.';
$l['userdata_email_already_in_use'] = 'Girmiş olduğunuz e-posta adresi, başka bir kullanıcı tarafından kullanılıyor veya engellenmiş olabilir. Lütfen farklı bir e-posta adresi giriniz.';
$l['userdata_dob_required'] = 'Doğum tarihinizi seçmediniz. Lütfen devam edebilmek için doğum tarihinizi seçiniz. (Doğum gününüzü ve Yaşınızı) Profil ayarlarınıza girerek diğer kullanıcıların görmesini engelleyebilirsiniz.';
$l['userdata_invalid_website'] = 'Girmiş olduğunuz website adresi geçersiz. Lütfen geçerli bir site adresi giriniz veya bu alanı boş bırakabilirsiniz.';
$l['userdata_invalid_icq_number'] = 'Girmiş olduğunuz ICQ numarası geçersiz. Lütfen geçerli bir ICQ numarası giriniz veya bu alanı boş bırakabilirsiniz.';
$l['userdata_invalid_birthday'] = 'Girmiş olduğunuz doğum tarihi geçersiz. Lütfen geçerli bir doğum tarihi giriniz veya bu alanı boş bırakabilirsiniz.';
$l['userdata_invalid_birthday_coppa'] = 'Yaşınızı doğrulamak için lütfen doğum yılınızı giriniz. (Doğum Tarihinizi ve Yaşınızı) Profil ayarlarınıza girerek diğer kullanıcıların görmesini engelleyebilirsiniz.';
$l['userdata_invalid_birthday_coppa2'] = 'Üyemiz olabilmeniz için en az 13 yaşında olmanız gerekiyor. Eğer 13 yaşın altında iseniz lütfen forum yöneticileri ile iletişim kurunuz.';
$l['userdata_invalid_birthday_privacy'] = 'Geçerli bir doğum günü gizlilik seçeneği seçin.';
$l['userdata_conflicted_birthday_privacy'] = 'You must specify your birth year if you choose to display age only as your birthday privacy.';
$l['userdata_invalid_referrer'] = 'Girmiş olduğunuz tavsiye eden kullanıcı adı sitemizde kayıtlı değil. Lütfen geçerli ve kayıtlı bir kullanıcı adı giriniz veya bu alanı boş bırakabilirsiniz.';
$l['userdata_invalid_language'] = 'Geçerli olmayan bir dil seçimi yaptınız. Lütfen geçerli ve mevcut dil seçeneklerinden birini seçiniz.';
$l['userdata_invalid_style'] = 'Seçtiğiniz stil geçersiz. Lütfen, geçerli bir stil seçiniz.';
$l['userdata_away_too_long'] = 'Belirttiğiniz uzaklaşma nedeni çok uzun. Bu alanda kullanabileceğiniz karakter limiti 200\'dür. Lütfen bu alandan {1} karakteri kaldırın.';
$l['userdata_missing_returndate'] = 'Dönüş tarihi alanının eksik olduğu tespit edildi. Lütfen belirtiğiniz Gün, Ay ve Yıl kısımlarının doğru olup olmadığını kontrol ediniz.';
$l['userdata_missing_required_profile_field'] = 'Sizin için "{1}" gerekli bu alanı seçmediniz veya boş bıraktınız. Lütfen bu alanı doldurunuz veya seçeneklerden birini seçiniz.';
$l['userdata_bad_profile_field_value'] = '"{1}" özel profil alanı için geçerli bir değer girmediniz. Devam etmeden önce lütfen geçerli bir değer giriniz.';
$l['userdata_bad_profile_field_values'] = 'Sizin için "{1}" gerekli bu seçeneklerden birini seçmediniz. Lütfen size sunulan seçenekler arasından bir tane seçiniz.';
$l['userdata_max_limit_reached'] = 'Sizin için "{1}" gerekli bu alanda geçersiz karakter kullandınız.  Lütfen {2} karakter uzunluğundan fazla girmeden bu alanı doldurunuz.';
$l['userdata_invalid_checkfield'] = 'Bu formun bir spam botu tarafından gönderildiği algılandı. Eğer bunun bir hata olduğunu düşünüyorsanız lütfen forum yöneticileri ile iletişim kurunuz.';
$l['userdata_invalid_postnum'] = 'Girmiş olduğunuz mesaj/yorum sayısı geçersiz. Lütfen geçerli bir mesaj sayısı giriniz veya bu alanı boş bırakabilirsiniz.';
$l['userdata_invalid_threadnum'] = 'Girmiş olduğunuz konu sayısı geçersiz. Lütfen geçerli bir konu sayısı giriniz veya bu alanı boş bırakabilirsiniz.';
$l['userdata_too_many_sig_images'] = 'Üzgünüz, imzanız güncellenemedi. Çünkü çok fazla resim içeriyor. Lütfen imzanızı güncellemek için resim limitine göre düzenleme yapınız.';
$l['userdata_too_many_sig_images2'] = '<strong>Not:</strong> İmza için izin verilen maksimum resim limiti: {1}.';
$l['userdata_sig_too_long'] = 'İmzanızın karakter uzunluğu çok fazla olduğu için güncellenemedi. Maksimum kullanılabilir karakter limiti: {1}';
$l['userdata_sig_remove_chars_plural'] = 'Lütfen, {1} adet karakter silip tekrar deneyiniz.';
$l['userdata_sig_remove_chars_singular'] = 'Lütfen, 1 adet karakter silip tekrar deneyiniz.';
