<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Fri, 24 Apr 2020 21:34:46 +0000
// --------------------------------------------------------------------------------

$l['warnings_reached_max_warnings_day'] = 'Bu kullanıcının daha önce {1} süreliğine uyarı aldığı görülüyor.<br /><br />Tekrar uyarı verebilmek için uyarı süresinin dolması gerekli.';
$l['warnings_error_invalid_user'] = 'Seçilen kullanıcı yok.';
$l['warnings_error_invalid_post'] = 'Seçilen mesaj yok.';
$l['warnings_error_cannot_warn_self'] = 'Kendi kendinize uyarı veremezsiniz.';
$l['warnings_error_user_reached_max_warning'] = 'Bu kullanıcı, maksimum uyarı limitini aştığı için uyarılamaz.';
$l['warnings_error_no_note'] = 'Bu uyarı için herhangi bir yönetici notu girmediniz.';
$l['warnings_error_invalid_type'] = 'Geçersiz bir uyarı türü seçtiniz.';
$l['warnings_error_cant_custom_warn'] = 'Kullanıcılara özel uyarı verme iznine sahip değilsiniz.';
$l['warnings_error_no_custom_reason'] = 'Özel uyarı için bir sebep girmediniz.';
$l['warnings_error_invalid_custom_points'] = 'Bu kullanıcının uyarı puanına ekleme yapmak veya uyarı puanını güncellemek için geçerli bir değer girmediniz. Ortalama: <b>0</b> ile <b>{1}</b> arası bir değer girmeniz gerekiyor.';
$l['warnings_error_invalid_expires_period'] = 'Geçersiz bir uyarı bitiş türü seçtiniz.';
