<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Fri, 24 Apr 2020 21:23:51 +0000
// --------------------------------------------------------------------------------

$l['logindata_invalidpwordusername'] = 'Geçersiz bir kullanıcı adı veya şifre girdiniz.<br /><br />Eğer şifrenizi unuttuysanız, <b><a rel="nofollow" href="member.php?action=lostpw">Buraya</a></b> tıklayıp yeni bir şifre talebinde bulunabilirsiniz.';
$l['logindata_invalidpwordusernameemail'] = 'Geçersiz bir e-posta veya şifre girdiniz.<br /><br />Eğer şifrenizi unuttuysanız, <b><a rel="nofollow" href="member.php?action=lostpw">Buraya</a></b> tıklayıp yeni bir şifre talebinde bulunabilirsiniz.';
$l['logindata_invalidpwordusernamecombo'] = 'Geçersiz bir kullanıcı adı, şifre veya e-posta adresi girdiniz.<br /><br />Eğer şifrenizi unuttuysanız, <b><a rel="nofollow" href="member.php?action=lostpw">Buraya</a></b> tıklayıp yeni bir şifre talebinde bulunabilirsiniz.';
$l['logindata_regimageinvalid'] = 'Girmiş olduğunuz resim doğrulama kodu yanlış. Lütfen kodu resimde göründüğü gibi giriniz. (Büyük / Küçük Harf Duyarlıdır)';
$l['logindata_regimagerequired'] = 'Lütfen sol tarafta görmüş olduğunuz resim üzerindeki harf ve rakamlardan oluşan Güvenlik Kodunu aşağıdaki metin kutusuna giriniz.';
