<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Fri, 24 Apr 2020 21:29:03 +0000
// --------------------------------------------------------------------------------

$l['postdata_invalid_user_id'] = 'Kullanıcı kimliği (ID\'si) yok. Lütfen geçerli bir kullanıcı (ID\'si) belirtiniz.';
$l['postdata_firstpost_no_subject'] = 'Konu başlığı girmediniz. Lütfen kısa ve açıklayıcı bir konu başlığı giriniz.';
$l['postdata_missing_subject'] = 'Konu başlığı eksik ya da bir başlık girmediniz. Lütfen kısa ve açıklayıcı bir konu başlığı giriniz.';
$l['postdata_missing_message'] = 'Konu içeriği olarak birşey yazmadınız. Lütfen kısa ve açıklayıcı bir konu içeriği yazınız.';
$l['postdata_message_too_long'] = 'Konu içeriği, <strong>({1})</strong> karakterden çok uzun. Lütfen daha kısa bir içerik yazınız.<br />(Şu anda girmiş olduğunuz içerik: {2}) karakter uzunluğunda.';
$l['postdata_message_too_short'] = 'Konu içeriği çok kısa. Lütfen, <strong>({1})</strong> karakterden daha uzun bir içerik yazınız.';
$l['postdata_subject_too_long'] = 'Konu başlığı çok uzun, <strong>(85)</strong> karakterden daha az bir konu başlığı giriniz. (Şu anki karakter sayısı: {1})';
$l['postdata_banned_username'] = 'Girdiğiniz kullanıcı adı kayıtlı olmayabilir. Farklı bir kullanıcı adı girin.';
$l['postdata_bad_characters_username'] = 'Girdiğiniz kullanıcı adı kötü karakterler içeriyor. Farklı bir kullanıcı adı girin.';
$l['postdata_invalid_username_length'] = 'Girdiğiniz kullanıcı adı geçersiz uzunlukta. Lütfen, {1} ve {2} karakter arası bir kullanıcı adı giriniz.';
$l['postdata_username_exists'] = 'Girdiğiniz kullanıcı adı zaten var, farklı bir kullanıcı adı giriniz.';
$l['postdata_post_flooding'] = 'Bir önceki mesajınızdan sonra, bu kadar hızlı art arda (flood) mesaj/yorum gönderemezsiniz. Lütfen <strong>({1})</strong> saniye daha bekleyiniz.';
$l['postdata_post_flooding_one_second'] = 'Bir önceki mesajınızdan sonra, bu kadar hızlı art arda (flood) mesaj/yorum gönderemezsiniz. Lütfen birkaç saniye daha bekleyiniz.';
$l['postdata_too_many_images'] = 'Girdiğiniz mesaj <strong>({1})</strong> resim içeriyor, mesaj başına sadece <strong>({2})</strong> resim ekleyebilirsiniz. Lütfen resim sayısını düşürün.';
$l['postdata_too_many_videos'] = 'Girdiğiniz mesaj <strong>({1})</strong> video içeriyor, mesaj başına sadece <strong>({2})</strong> video ekleyebilirsiniz. Lütfen video sayısını düşürün.';
$l['postdata_invalid_prefix'] = 'Seçilen ön ek geçersiz. Lütfen geçerli bir ön ek seçiniz.';
$l['postdata_require_prefix'] = 'Bu forum için ayarlanmış sabit konu ön ekinin seçilmesi gerekli. Lütfen geçerli bir ön ek seçiniz.';
$l['thread_closed'] = 'Konu Kapatıldı';
$l['thread_opened'] = 'Konu Açıldı';
$l['thread_stuck'] = 'Konu Sabitlendi';
$l['thread_unstuck'] = 'Konu Sabitlikten Kaldırıldı';
