<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBB
// Language pack translators website : https://mybbturkce.com
// Compatible version of MyBB : 1818
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Mon, 19 Nov 2018 01:03:48 +0000
// --------------------------------------------------------------------------------

$l['gomobile'] = 'MyBB GoMobile';
$l['gomobile_desc'] = 'MyBB için GoMobile eklentisi. Kullanıcılarınıza mobil cihazlar için düzenli ifade ve tema kullanımı sağlar.<br />Türkçe Çeviri: <a href="https://mybbturkce.com" target="_blank"><b>MyBBTurkce.com</b></a>';
$l['gomobile_settings_mobile_name_title'] = 'Mobil Forum İsmi';
$l['gomobile_settings_mobile_name'] = 'Navbarda gösterilecek olan forum adı, başlığınız uzun ise bu ayarı kullanabilirsiniz. (Bu kısımda dilerseniz HTML kullanabilirsiniz).';
$l['gomobile_settings_redirect_enabled_title'] = 'Portal Yönlendirme Etkinleştir?';
$l['gomobile_settings_redirect_enabled'] = 'Gomobile için portal yönlendirmesini aktif edebilir veya devre dışı bırakabilirsiniz. Bu ayar aynı zamanda otomatik yönledirmede kullanıcılara sizin seçmiş olduğunuz bir sayfaya yönlenmelerini de sağlar.';
$l['gomobile_settings_redirect_location_title'] = 'Yönlendirme Adresi';
$l['gomobile_settings_redirect_location'] = 'Kullanıcıların yönlendirilmeleri için bir sayfa giriniz. Yukarıdaki ayarı devre dışı bıraktıysanız bu ayar aktif olmayacaktır!';
$l['gomobile_settings_theme_id_title'] = 'Tema ID';
$l['gomobile_settings_theme_id'] = 'Aşağıdaki alana, GoMobile temasının IDsi giriniz. Bu kullanıcılarınızın yönlendirme sırasında tema seçimi yapmalarına olanak sağlar.';
$l['gomobile_settings_permstoggle_title'] = 'Tema izinleri kullanın?';
$l['gomobile_settings_permstoggle'] = 'Tema özel kullanım izinlerini kullanmak için bu ayarı etkinleştirin. Devre dışı bırakılırsa, tüm gruplar için mobil sürümü kullanmak mümkün olacaktır. Tema izinleri gerekmedikçe HAYIR seçilmesi önerilir.';
$l['gomobile_settings_homename_title'] = 'Anasayfa Adı';
$l['gomobile_settings_homename'] = 'Bu ayar GoMobile footer kısmı için metin alanıdır. Bu kısma olabildiğince kısa metin giriniz.';
$l['gomobile_settings_homelink_title'] = 'Anasayfa Link';
$l['gomobile_settings_homelink'] = 'Footerda gösterilmesi için ana sayfa url adresini giriniz.';
$l['gomobile_settings_strings_title'] = 'Kullanıcı Arayüz Aygıtları';
$l['gomobile_settings_strings'] = 'Yeni bir satır ile ayırarak, kontrol etmek istediğiniz aygıtları girin ve ardından mobil tema gönderin. Normalde bunu ayarlamak gerekmez.';
$l['gomobile_mobile_version'] = 'Mobil Sürüm';
$l['gomobile_switch_full'] = 'Tam Sürüme Geç';
$l['gomobile_redirect_notice'] = 'Yönlendirme Bildirimi';
$l['gomobile_posted_from'] = 'Mobil cihazından gönderildi.';
$l['gomobile_ucp'] = 'KP';
$l['gomobile_mcp'] = 'MKP';
$l['gomobile_acp'] = 'AKP';
$l['gomobile_pms'] = 'ÖM';
$l['gomobile_logout'] = 'Çıkış';
$l['gomobile_last'] = 'Son';
$l['gomobile_lastby'] = 'Son Gönderen:';
$l['gomobile_post_edit'] = 'Düzenle';
$l['gomobile_post_delete'] = 'Sil';
$l['gomobile_post_quote'] = 'Alıntı';
$l['gomobile_post_warn'] = 'Uyar';
$l['gomobile_post_pm'] = 'Ö.M';
$l['gomobile_page'] = 'Sayfa:';
$l['gomobile_of'] = 'of';
$l['gomobile_copyrights'] = 'Türkçe Çeviri <a href=\'https://mybbturkce.com\' target=\'_blank\'>MyBB</a>, Yazılım <a href=\'http://mybb.com\' target=\'_blank\'>MyBBGroup</a>';
$l['gomobile_showsig'] = 'İmzanız kullanılsın mı?';
$l['gomobile_disablesmilies'] = 'Bu konu/yorum için ifadeler devre dışı bırakılsın mı?';
$l['gomobile_savecopy'] = 'Kopyası Kaydedilsin mi?';
$l['gomobile_receipt'] = 'Konu hakkında bilgi verilsin mi?';
$l['gomobile_modclose'] = 'Konuyu Kapat?';
$l['gomobile_modstick'] = 'Konuyu Sabitle?';
$l['gomobile_send'] = 'Gönder';
$l['gomobile_unreadreports'] = 'Moderatör Notu: Okunmuş yorum-ları rapor et.';
$l['gomobile_bbclosed'] = 'Konu kapatılmıştır.';
$l['gomobile_nosubs'] = 'Abonelik yok.';
$l['gomobile_newsubs'] = 'Abone olunan konularda yeni yorum var.';
$l['gomobile_redirect_portal'] = 'Yönetim Gomobile sürümünü devre dışı bıraktı. Şimdi alternatif olarak başka bir sayfaya yönlendiriliyorsunuz...';
$l['gomobile_use_mobile_version'] = 'Siteyi bir dahaki ziyaretimde mobil olarak göster.';
$l['gomobile_clear_cookies'] = 'çerezleri temizle';
$l['gomobile_switched_version'] = 'Diğer sürüme aktarılıyorsunuz.<br />Lütfen aktarım işlemi bitene kadar bekleyiniz.';
$l['gomobile_lastpost'] = 'Son Yorum: ';
$l['gomobile_orderby'] = 'Gönderen: ';
$l['gomobile_forum'] = 'Forum: ';
$l['gomobile_by'] = 'Yazar: ';
$l['gomobile_jump_fpost'] = 'İlk Yorum';
$l['gomobile_jump_lpost'] = 'Son Yorum';
$l['gomobile_votes'] = 'Oylar';
$l['gomobile_error_message'] = 'Bu sayfaya erişmek için izniniz yok. Aşağıdan giriş yaparak tekrar deneyin. Eğer yine işe yaramazsa burada olmamanız gerekiyordur.';
$l['gomobile_ucp_username'] = 'Kullanıcı Adı:';
$l['gomobile_ucp_avatar'] = 'Avatar:';
$l['gomobile_ucp_inbox'] = 'Gelen Kutusu';
$l['gomobile_pm_reply'] = 'Cevapla';
$l['gomobile_pm_delete'] = 'Sil';
$l['gomobile_pm_forward'] = 'Sevket';
$l['gomobile_pm_replyall'] = 'Çoklu Cevap';
$l['gomobile_mcp_until'] = ' - Kadar: ';
$l['gomobile_mcp_reason'] = 'Sebep: ';
$l['gomobile_mcp_controls'] = 'Ayarlar';
$l['gomobile_mcp_pid'] = '# Yorumlar';
$l['gomobile_mcp_in'] = ' -de ';
