<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Sun, 26 Apr 2020 09:15:59 +0000
// --------------------------------------------------------------------------------

$l['boardstats'] = 'Forum İstatistikleri';
$l['new_posts'] = 'Yeni Yorum Var';
$l['no_new_posts'] = 'Yeni Yorum Yok';
$l['forum_closed'] = 'Forum Kapalı';
$l['forum_unapproved_posts_count'] = 'Şu an forumda {1} adet onaylanmamış yorum bulunmaktadır.';
$l['forum_unapproved_post_count'] = 'Şu an forumda 1 adet onaylanmamış yorum bulunmaktadır.';
$l['forum_unapproved_threads_count'] = 'Şu an forumda {1} adet onaylanmamış konu bulunmaktadır.';
$l['forum_unapproved_thread_count'] = 'Şu an forumda 1 adet onaylanmamış konu bulunmaktadır.';
$l['forumteam'] = 'Forum Yöneticileri';
$l['forumstats'] = 'Forum İstatistikleri';
$l['todays_birthdays'] = 'Bugün Doğum Günü Olanlar';
$l['birthdayhidden'] = 'Gizli';
$l['quick_login'] = 'Hızlı Giriş Yap:';
$l['index_logout'] = 'Çıkış Yap';
$l['private_messages'] = 'Özel Mesajlar';
$l['pms_new'] = 'Son ziyaretinizden bu yana toplam {1} adet yeni mesajınız var.';
$l['pms_unread_total'] = '(Şu an {1} okunmamış ve toplam {2} adet mesajınız bulunmaktadır.)';
$l['stats_posts_threads'] = 'Toplam <strong>{2}</strong> Konu <strong>{1}</strong> Yorum Mevcut.';
$l['stats_numusers'] = 'Şu anda Forumumuza Kayıtlı <strong>{1}</strong> Üyemiz Var. ';
$l['stats_newestuser'] = 'Son Kayıt Olan Kullanıcı: <strong>{1}</strong>, Hoşgeldin!';
$l['stats_mostonline'] = 'Online Rekorumuz: <strong>{1}</strong> Kullanıcı İle {2} Tarihinde, Saat {3} Gerçekleşmiştir.';
$l['whos_online'] = 'Kimler Çevrimiçi';
$l['complete_list'] = 'Ayrıntılı Liste';
$l['online_online_plural'] = 'Kullanıcı';
$l['online_online_singular'] = 'Kullanıcı';
$l['online_member_plural'] = 'Kullanıcı';
$l['online_member_singular'] = 'Kullanıcı';
$l['online_anon_plural'] = '';
$l['online_anon_singular'] = '';
$l['online_guest_plural'] = 'Ziyaretçi';
$l['online_guest_singular'] = 'Ziyaretçi';
$l['online_note'] = 'Şu an <strong>{4}</strong> üye, <strong>{8}</strong> ziyaretçi aktif.';
$l['subforums'] = 'Alt Forumlar:';
$l['board_stats_link_separator'] = ' | ';
