<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Mon, 27 Apr 2020 20:14:59 +0000
// --------------------------------------------------------------------------------

$l['nav_memberlist'] = 'Üye Listesi';
$l['memberlist_disabled'] = 'Üye Listesi, forum yöneticisi tarafından kullanıma kapatılmıştır.';
$l['member_list'] = 'Üye Listesi';
$l['avatar'] = 'Avatar';
$l['username'] = 'Kullanıcı Adı';
$l['joined'] = 'Üyelik Tarihi';
$l['lastvisit'] = 'Son Ziyareti';
$l['posts'] = 'Yorum';
$l['threads'] = 'Konu';
$l['referrals'] = 'Referans';
$l['search_members'] = 'Üye Listesinde Ara/Bul';
$l['website'] = 'Web Site';
$l['sort_by'] = 'Listeleme Seçenekleri';
$l['contains'] = 'Arama Terimi:';
$l['exactly'] = "Kesinlikle:";
$l['sort_by_username'] = 'Kullanıcı Adına Göre Listele';
$l['sort_by_regdate'] = 'Üyelik Tarihine Göre Listele';
$l['sort_by_lastvisit'] = 'Son Ziyarete Göre Listele';
$l['sort_by_posts'] = 'Yorum Sayısına Göre Listele';
$l['sort_by_threads'] = 'Konu Sayısına Göre Listele';
$l['sort_by_referrals'] = 'Referans Sayısına Göre Listele';
$l['order_asc'] = 'Artan';
$l['order_desc'] = 'Azalan';
$l['asc'] = '+';
$l['desc'] = '-';
$l['forumteam'] = 'Forum Yöneticileri';
$l['advanced_search'] = 'Gelişmiş Arama Yap';
$l['nav_memberlist_search'] = 'Gelişmiş Üye Arama';
$l['search_member_list'] = 'Gelişmiş Üye Arama';
$l['search_criteria'] = 'Arama Seçenekleri';
$l['begins_with'] = 'Harf ile Başlayan';
$l['username_contains'] = 'Üye Adı İçeren';
$l['search_website'] = 'Website Adresine Göre';
$l['search_skype'] = 'Skype Adresine Göre';
$l['search_google'] = 'Google Hangouts Adresine Göre';
$l['search_icq'] = 'ICQ Numarasına Göre';
$l['search_options'] = 'Diğer Arama Seçenekleri';
$l['per_page'] = 'Sayfa Başına Listeleme';
$l['search'] = 'Aramayı Başlat';
$l['error_no_members'] = '<p>Aradığınız kriterlere uygun, hiç bir kullanıcı kaydı bulunamadı.</p><p>Lütfen, farklı bir arama terimi girerek tekrar deneyiniz.</p>';
$l['a'] = 'A';
$l['b'] = 'B';
$l['c'] = 'C';
$l['d'] = 'D';
$l['e'] = 'E';
$l['f'] = 'F';
$l['g'] = 'G';
$l['h'] = 'H';
$l['i'] = 'I';
$l['j'] = 'J';
$l['k'] = 'K';
$l['l'] = 'L';
$l['m'] = 'M';
$l['n'] = 'N';
$l['o'] = 'O';
$l['p'] = 'P';
$l['q'] = 'Q';
$l['r'] = 'R';
$l['s'] = 'S';
$l['t'] = 'T';
$l['u'] = 'U';
$l['v'] = 'V';
$l['w'] = 'W';
$l['x'] = 'X';
$l['y'] = 'Y';
$l['z'] = 'Z';
