<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Tue, 19 May 2020 05:50:10 +0000
// --------------------------------------------------------------------------------

$l['nav_helpdocs'] = 'Yardım Belgeleri';
$l['nav_smilies'] = 'Gülücük Listeleme';
$l['nav_syndication'] = 'Son Konu Birliği (RSS)';
$l['buddy_list'] = 'Arkadaş Listesi';
$l['online'] = 'Çevrimiçi';
$l['online_none'] = 'Çevrimiçi arkadaşınız yok.';
$l['offline'] = 'Çevrimdışı';
$l['offline_none'] = 'Çevrimdışı arkadaşınız yok.';
$l['delete_buddy'] = 'X';
$l['pm_buddy'] = 'ÖM Gönder';
$l['last_active'] = '{1}';
$l['close'] = 'Kapat';
$l['no_buddies'] = '<em>Arkadaş listeniz şu anda boş. Arkadaş listene kullanıcı eklemek için Kullanıcı KP kullanın veya bir kullanıcı profilini ziyaret edin.</em>';
$l['help_docs'] = 'Yardım Belgeleri';
$l['search_help_documents'] = 'Yardım Belgelerinde Ara';
$l['search_by_name'] = 'İsme göre ara';
$l['search_by_document'] = 'Belgeye göre ara';
$l['enter_keywords'] = 'Aranacak kelime ...';
$l['search'] = 'Arama Yap';
$l['redirect_searchresults'] = 'Teşekkürler, aramanız gönderildi ve şimdi sonuçlar listesine yönlendirileceksiniz.';
$l['search_results'] = 'Arama Sonuçları';
$l['help_doc_results'] = 'Yardım Belgesi Sonuçları';
$l['document'] = 'Belge';
$l['error_nosearchresults'] = 'Üzgünüz, aradığınız sorgu bilgileri kullanılarak hiç bir sonuç bulunamadı. Lütfen aranacak kelimeyi yeniden tanımlayın ve tekrar deneyin.';
$l['no_help_results'] = 'Üzgünüz, aradığınız sorgu bilgileri kullanılarak hiç bir sonuç bulunamadı.';
$l['error_helpsearchdisabled'] = 'Yardım belgelerinde arama yapma özelliği yönetici tarafından devre dışı bırakıldı.';
$l['smilies_listing'] = 'Gülücük Listeleme';
$l['name'] = 'İsim';
$l['abbreviation'] = 'Kısaltma';
$l['click_to_add'] = 'Mesajınıza eklemek için bir ifadeyi tıklayın';
$l['close_window'] = 'Kapat';
$l['no_smilies'] = 'Şu anda kullanılabilir ifade yok.';
$l['who_posted'] = 'Kim Gönderdi ?';
$l['total_posts'] = 'Toplam Yorum:';
$l['user'] = 'Kullanıcı';
$l['num_posts'] = '# Yorumlar';
$l['forum_rules'] = '{1} - Kurallar';
$l['error_invalid_limit'] = 'Girdiğiniz feed öğesi sınırı geçersiz. Lütfen geçerli bir sınır belirtin.';
$l['syndication'] = 'Son Konular RSS Beslemesi';
$l['syndication_generated_url'] = 'Oluşturulan RSS URL\'si:';
$l['syndication_note'] = 'Bu kısımdan kendinize özel RSS Takip URL bağlantıları oluşturabilirsiniz.<br />Bu bağlantıyı örneğin; <i><a style="color: #333;" href="http://MyBBTurkce.com" target="_blank">MyBB Türkçe</a></i> sitenizdeki widget araçları için RSS takip/akışı aracı olarak kullanabilirsiniz.<br />Bunun için (Tüm Forumlar RSS) sekmesini seçebilir veya menüdeki seçeneklerden besleme almak istediğiniz tek bir kategoriyi/forumu seçebilirsiniz.';
$l['syndication_forum'] = 'RSS Besleme URL\'si oluşturulacak forumlar:';
$l['syndication_forum_desc'] = 'Lütfen sağ taraftaki menüden beslemesini almak istediğiniz bir forum seçiniz. Çoklu veya özel seçim için <b>(Ctrl)</b> tuşunu kullanabilirsiniz. Tüm forumların beslemesini almak için <b>(Tüm Forumlar RSS)</b> sekmesine tıklayınız.';
$l['syndication_version'] = 'RSS Feed Versiyon Seçimi:';
$l['syndication_version_desc'] = 'Lütfen sağ taraftaki seçeneklerden oluşturmak istediğiniz RSS beslemesinin sürümünü seçiniz.';
$l['syndication_version_atom1'] = 'Atom 1.0';
$l['syndication_version_json1'] = 'JSON Beslemesi 1';
$l['syndication_version_rss2'] = 'RSS 2.00 (Varsayılan Sürüm)';
$l['syndication_generate'] = 'RSS Besleme URL\'sini oluştur';
$l['syndication_limit'] = 'Limit Ayarları:';
$l['syndication_limit_desc'] = 'Sağ taraftan, sayfa başına gösterilecek konu sayısını giriniz. Sayfa başına gösterilecek maksimum konu sayısı <b>50</b>\'yi geçmemesi tavsiye edilir.';
$l['syndication_threads_time'] = 'Sayfa başına gösterilecek konu sayısını giriniz. (varsayılan seçim 15)';
$l['syndicate_all_forums'] = 'Tüm Forumlar RSS';
$l['redirect_markforumread'] = 'Seçilen forumlar okundu olarak işaretlendi.';
$l['redirect_markforumsread'] = 'Tüm forumlar okundu olarak işaretlendi.';
$l['redirect_forumpasscleared'] = 'Bu forum için kullanılan şifre başarılı olarak temizlendi.';
$l['redirect_cookiescleared'] = 'Tüm çerezler başarılı olarak silindi.';
$l['error_invalidforum'] = 'Geçersiz forum';
$l['error_invalidhelpdoc'] = 'Belirtilen Yardım Belgesi Bulunamıyor.';
$l['error_invalidsearch'] = 'Geçersiz bir arama tespit edildi. Lütfen geri dönün ve tekrar deneyin.';
$l['error_no_search_support'] = 'Veritabanı sistemi bu aramayı desteklemiyor.';
$l['error_searchflooding'] = 'Üzgünüz, fakat arama sistemini sadece {1} saniyede bir kullanabilirsiniz. Tekrar arama yapabilmek için lütfen, {2} saniye daha bekleyin.';
$l['error_searchflooding_1'] = 'Üzgünüz, fakat arama sistemini sadece {1} saniyede bir kullanabilirsiniz. Tekrar arama yapabilmek için lütfen, 1 saniye daha bekleyin.';
$l['dst_settings_updated'] = 'Yaz saati zaman ayarları otomatik olarak ayarlanmıştır.<br /><br />Şimdi Forum Ana Sayfasına Yönlendiriliyorsunuz...';
