<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Sat, 25 Apr 2020 04:55:32 +0000
// --------------------------------------------------------------------------------

$l['nav_newreply'] = 'Yeni Yorum';
$l['post_reply_to'] = '{1} - Yeni Yorum Gönder';
$l['post_new_reply'] = 'Yeni Yorum Gönder';
$l['reply_to'] = '{1}: Konusuna Yorum Yaz';
$l['post_subject'] = 'Yorum Başlığı:';
$l['your_message'] = 'Yorum İçeriği:';
$l['post_options'] = 'İmza ve İfade Yönetimi:';
$l['options_sig'] = '<strong>İmza Kullanımı:</strong> İmzanız gösterilsin mi?';
$l['options_emailnotify'] = '<strong>E-posta Bildirimi:</strong> Konuya yazılan her cevap için otomatik e-posta bildirimi almak istiyorum.';
$l['options_disablesmilies'] = '<strong>İfade Kullanımı:</strong> İfadeler devre dışı bırakılsın mı?';
$l['post_reply'] = 'Yeni Yorumu Gönder';
$l['preview_post'] = 'Önizleme Yap';
$l['mod_options'] = 'Moderatör Seçenekleri:';
$l['close_thread'] = '<strong>Konuyu Kapat:</strong> Konu kapatılsın mı?';
$l['stick_thread'] = '<strong>Konuyu Sabitle:</strong> Konu sabitlensin mi?';
$l['forum_rules'] = '{1} - Kurallar';
$l['thread_review'] = 'Konuya Yazılan Yorumlar (Önce En Yeni)';
$l['thread_review_more'] = 'Bu konuya yazılmış {1}\'dan fazla yorum var. <a href="{2}">Konunun tamamını okuyun.</a>';
$l['posted_by'] = 'Yazan';
$l['draft_saved'] = 'Yeni yorumunuz başarılı olarak taslaklara kaydedildi.<br />Şimdi taslak listenize yönlendiriliyorsunuz...';
$l['error_post_already_submitted'] = 'Siz bu konuya zaten yorum yazmışsınız. Lütfen yorumunuzu okumak için konuyu ziyaret ediniz.';
$l['multiquote_external_one'] = 'Bu Konuya Ait 1 Yorum Seçtiniz.';
$l['multiquote_external'] = 'Bu Konuya Ait {1} Yorum Seçtiniz.';
$l['multiquote_external_one_deselect'] = 'Bu Yorumun Seçimini Kaldır';
$l['multiquote_external_deselect'] = 'Bu Yorumların Seçimini Kaldır';
$l['multiquote_external_one_quote'] = 'Bu Yorumu Alıntı Yap';
$l['multiquote_external_quote'] = 'Çoklu Alıntı Yap';
$l['redirect_newreply'] = 'Teşekkürler, yorumunuz başarılı olarak gönderildi.';
$l['redirect_newreply_moderation'] = '<br />Forum yöneticisi, tüm yeni konu ve yorumları moderasyon işlemi gerektirecek şekilde ayarlamış.<br />Şimdi konuya geri yönlendiriliyorsunuz...';
$l['redirect_newreply_post'] = '<br />Şimdi yorumunuza geri yönlendiriliyorsunuz...';
$l['redirect_newreplyerror'] = 'Üzgünüz, yorumunuz içerik yetersizliğinden reddedildi.<br />Şimdi konuya geri yönlendiriliyorsunuz...';
$l['redirect_threadclosed'] = 'Bu konuya yorum yazamazsınız. Çünkü bu konu forum yöneticileri tarafından kapatılmıştır.';
$l['error_post_noperms'] = 'Bu taslağı düzenlemek için gerekli yetkiniz yok.';
$l['error_stop_forum_spam_spammer'] = 'Üzgünüz, {1} veritabanımızda kayıtlı bilinen bir spam olarak algılandı. Eğer bunun bir hata olduğunu düşünyorsanız lütfen, iletişim bölümünden forum yöneticisi ile irtibat kurunuz.';
$l['error_stop_forum_spam_fetching'] = 'Üzgünüz, hesabınızın bilinen bir spam olup olmadığını sorgulama sırasında veritabanında bir hata oluştu. Lütfen daha sonra tekrar deneyiniz.';
$l['error_suspendedposting'] = 'Üzgünüz, yeni konu ve yorum gönderimleriniz; {1} askıya alındı.<br /><br />Askıya Alınma Tarihi: {2}';
$l['error_suspendedposting_temporal'] = '{1} tarihine kadar';
$l['error_suspendedposting_permanent'] = 'Süresiz olarak';
