<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1824
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Fri, 07 May 2021 15:39:43 +0000
// --------------------------------------------------------------------------------

$l['nav_online'] = 'Kimler Çevrimiçi';
$l['nav_onlinetoday'] = 'Son 24 Saat İçinde Çevrimiçi Olanlar';
$l['viewing_announcements'] = '<a rel="nofollow" href="{1}">{2}</a> Duyurusunu Okuyor';
$l['viewing_announcements2'] = 'Forum Duyurularını İnceliyor';
$l['viewing_attachment'] = 'Eklentiyi İndiriyor';
$l['viewing_attachment2'] = '<a href="{3}">{2}</a> Konusundaki <a rel="nofollow" href="attachment.php?aid={1}" target="_blank">Eklenti</a>yi İndiriyor';
$l['viewing_calendar'] = '<a rel="nofollow" href="calendar.php">Takvim</a>i Görüntülüyor';
$l['viewing_event'] = 'Etkinlik İnceliyor';
$l['viewing_event2'] = '<a rel="nofollow" href="{1}">{2}</a> Etkinliğini İnceliyor';
$l['adding_event'] = 'Yeni Bir <a rel="nofollow" href="calendar.php?action=addevent">Etkinlik</a> Ekliyor';
$l['editing_event'] = 'Etkinlik Düzenliyor';
$l['viewing_contact_us'] = '<a rel="nofollow" href="contact.php">İletişim Sayfası</a>nı görüntülüyor.';
$l['editing_post'] = 'Yorum Düzenliyor';
$l['viewing_forum'] = 'Forumu Görüntülüyor';
$l['viewing_forum2'] = '<a href="{1}">{2}</a> Forumunu Görüntülüyor';
$l['forum_redirect_to'] = '<a rel="nofollow" href="{1}">{2}</a> Sayfasına Yönlendiriliyor';
$l['viewing_index'] = '<a href="index.php">Forum Ana Sayfası</a>nı Görüntülüyor';
$l['activating_account'] = 'Kullanıcı Hesabını Aktifleştiriyor';
$l['viewing_profile'] = 'Profilini İnceliyor';
$l['viewing_profile2'] = '<a rel="nofollow" href="{1}">{2}</a> Adlı Kullanıcının Profilini İnceliyor';
$l['registering'] = 'Foruma <a rel="nofollow" href="member.php?action=register">Kayıt Ol</a>uyor';
$l['logging_in'] = 'Foruma <a rel="nofollow" href="member.php?action=login">Giriş</a> Yapıyor';
$l['logging_in_plain'] = 'Foruma Giriş Yapıyor';
$l['logging_out'] = 'Çıkış Yapıyor';
$l['emailing_user'] = 'Bir Kullanıcıya E-posta Gönderiyor';
$l['rating_user'] = 'Bir Kullanıcıya Oy Veriyor';
$l['viewing_memberlist'] = '<a rel="nofollow" href="memberlist.php">Üye Listesi</a>ni İnceliyor';
$l['viewing_whoposted'] = 'Yorum Gönderenleri İnceliyor';
$l['viewing_whoposted2'] = '<a rel="nofollow" href="{1}">{2}</a> Konusuna Kimlerin Yorum Yazdığına Bakıyor';
$l['marking_read'] = '<a rel="nofollow" href="misc.php?action=markread&amp;my_post_key={1}">Forumları Okundu Olarak Onaylıyor</a>';
$l['viewing_helpdocs'] = '<a rel="nofollow" href="misc.php?action=help">Yardım Belgeleri</a>ni İnceliyor';
$l['viewing_buddylist'] = '<a rel="nofollow" href="#" onclick="MyBB.popupWindow(\\\'/misc.php?action=buddypopup&amp;modal=1\\\'); return false;">Arkadaş Listesi</a>ni İnceliyor';
$l['viewing_smilies'] = '<a rel="nofollow" href="misc.php?action=smilies">İfade Listesi</a>ni İnceliyor';
$l['viewing_syndication'] = '<a rel="nofollow" href="misc.php?action=syndication">RSS Besleme</a> Sayfasını İnceliyor';
$l['replying_thread'] = 'Konuya Yorum Yazıyor';
$l['replying_thread2'] = '<a href="{1}">{2}</a> Konusuna Yorum Yazıyor';
$l['posting_thread'] = 'Yeni Konu Açıyor';
$l['posting_thread2'] = '<a href="{1}">{2}</a> Forumunda Yeni Konu Açıyor';
$l['viewing_wol'] = '<a rel="nofollow" href="online.php">Kimler Çevrimiçi</a> Sayfasını İnceliyor';
$l['viewing_woltoday'] = '<a rel="nofollow" href="online.php?action=today">Son 24 Saat İçinde Çevrimiçi Olanlar</a>ı İnceliyor';
$l['creating_poll'] = 'Foruma Yeni Anket Açıyor';
$l['editing_poll'] = 'Anket Düzenliyor';
$l['viewing_pollresults'] = 'Anket Sonuçlarını İnceliyor';
$l['voting_poll'] = 'Bir Ankete Oy Veriyor';
$l['using_modtools'] = 'Yönetici Araçlarını Kullanıyor';
$l['sending_pm'] = 'Özel Mesaj Gönderiyor';
$l['reading_pm'] = 'Özel Mesaj Okuyor';
$l['editing_pmfolders'] = 'Ö.M Klasörünü Düzenliyor';
$l['using_pmsystem'] = 'Özel Mesaj Sistemini Kullanıyor';
$l['reporting_post'] = 'Bir Yorumu Rapor Ediyor';
$l['searching_forum'] = '<a rel="nofollow" href="search.php">Arama</a> {1}';
$l['reading_thread'] = 'Konu Okuyor';
$l['reading_thread2'] = '<a href="{1}">{2}</a> {3} Konusunu Okuyor';
$l['viewing_team'] = '<a rel="nofollow" href="showteam.php">Forum Yöneticileri</a> Sayfasını İnceliyor';
$l['viewing_stats'] = '<a rel="nofollow" href="stats.php">Forum İstatistikleri</a>ni İnceliyor';
$l['updating_profile'] = '<a rel="nofollow" href="usercp.php?action=profile">Profilini Güncelliyor</a>';
$l['updating_options'] = '<a rel="nofollow" href="usercp.php?action=options">Profil Seçenekleri</a>ni Güncelliyor';
$l['editing_signature'] = '<a rel="nofollow" href="usercp.php?action=editsig">İmzasını Düzenliyor</a>';
$l['changing_avatar'] = '<a rel="nofollow" href="usercp.php?action=avatar">Avatarını Değiştiriyor</a>';
$l['viewing_subscriptions'] = '<a rel="nofollow" href="usercp.php?action=subscriptions">Takip Ettiği Konular</a>ı İnceliyor';
$l['editing_pad'] = '<a rel="nofollow" href="usercp.php?action=notepad">Kişisel Not Defteri</a>ni Düzenliyor';
$l['editing_password'] = '<a rel="nofollow" href="usercp.php?action=password">Şifre</a>sini Değişiyor';
$l['user_cp'] = '<a rel="nofollow" href="usercp.php">Kullanıcı Kontrol Paneli</a>ni Görüntülüyor';
$l['viewing_portal'] = '<a rel="nofollow" href="portal.php">Portal Sayfası</a>nı İnceliyor';
$l['viewing_noperms'] = 'İzni Olmayan Bir Sayfaya Bakıyor';
$l['unknown_location'] = '<a rel="nofollow" href="{1}">Bilinmeyen Sayfa</a>';
$l['giving_reputation'] = '<a rel="nofollow" href="{1}">{2}</a> Adlı Kullanıcıya Rep Puanı Veriyor';
$l['viewing_reputation_report'] = '<a rel="nofollow" href="{1}">{2}</a> Adlı Kullanıcının Rep Puanı Tablosuna Bakıyor';
$l['viewing_reputation_report2'] = 'Rep Puanlarına Bakıyor';
$l['member_resendactivation'] = 'Aktivasyon Mailini Tekrar Talep Ediyor';
$l['member_lostpw'] = '<a rel="nofollow" href="member.php?action=lostpw">Kayıp Şifre</a>sini Yeniliyor';
$l['sending_thread'] = 'Bir Arkadaşına Konu Gönderiyor';
$l['page'] = 'Sayfa';
$l['users_online'] = 'Kimler Çevrimiçi';
$l['on_username'] = 'Kullanıcı';
$l['time'] = 'Zaman';
$l['location'] = 'Yer';
$l['online_today'] = 'Son 24 Saat İçinde Çevrimiçi Olanlar';
$l['refresh_page'] = 'Sayfayı Yenile';
$l['online_online_plural'] = 'Kullanıcı';
$l['online_online_singular'] = 'Kullanıcı';
$l['online_member_plural'] = 'Kullanıcı';
$l['online_member_singular'] = 'Kullanıcı';
$l['online_anon_plural'] = '';
$l['online_anon_singular'] = '';
$l['online_guest_plural'] = 'Ziyaretçi';
$l['online_guest_singular'] = 'Ziyaretçi';
$l['online_count'] = 'Son {3} Dakika İçinde {1} Kullanıcı Aktif Oldu. Şu an Forumda: [{4} Kayıtlı, {6} Gizli  ve {8} Ziyaretçi] Bulunmaktadır.';
$l['ip'] = 'IP:';
$l['resolves_to'] = 'Host Adı:';
$l['if_resolvable'] = '[Çözümlenebiliyorsa Eğer Gösterilir]';
$l['admin_options'] = 'Admin Seçenekleri:';
$l['search_regip_users'] = 'Bu IP Adresiyle Kayıt Olanları Bul';
$l['search_postip_users'] = 'Bu IP Adresiyle Gönderilmiş Konu Ve Yorumları Bul';
$l['lookup'] = '[Ayrıntılar]';
$l['member_online_today'] = 'Bugün <strong>1</strong> Üye Aktifti';
$l['members_were_online_today'] = 'Bugün <strong>{1}</strong> Üye Aktifti';
$l['member_online_hidden'] = ' ({1} Gizli Kullanıcı)';
$l['members_online_hidden'] = ' ({1} Gizli Kullanıcı)';
$l['rating_thread'] = 'Konu Değerlendiriyor';
$l['managing_favorites'] = 'Favori Konularını Yönetiyor';
$l['managing_subscriptions'] = 'Takip Ettiği Konuları Yönetiyor';
$l['managing_group'] = 'Bağlı Olduğu Kullanıcı Grubunu Yönetiyor';
$l['viewing_modcp'] = 'Mod Panelini İnceliyor';
$l['viewing_modlogs'] = 'Moderatör Kayıtlarını İnceliyor';
$l['managing_announcements'] = 'Forum Duyurularını Yönetiyor';
$l['search_for_user'] = 'Bir Kullanıcı Araması Yapıyor';
$l['managing_warninglogs'] = 'Uyarı Kayıtlarını Yönetiyor';
$l['searching_ips'] = 'IP Araması Yapıyor';
$l['viewing_reports'] = 'Rapor Edilen Konuları İnceliyor';
$l['adding_announcement'] = 'Yeni Bir Forum Duyurusu Ekliyor';
$l['deleting_announcement'] = 'Bir Duyuruyu Siliyor';
$l['editing_announcement'] = 'Bir Duyuruyu Düzenliyor';
$l['managing_modqueue'] = 'Moderasyon İşlemlerini Yönetiyor';
$l['editing_user_profiles'] = 'Kullanıcı Profili Düzenliyor';
$l['managing_bans'] = 'Yasaklı Kullanıcıları Yönetiyor';
$l['revoking_warning'] = 'Bir Uyarıyı İptal Ediyor';
$l['warning_user'] = 'Bir Kullanıcıyı Uyarıyor';
$l['viewing_warning'] = 'Bir Uyarıyı İnceliyor';
$l['managing_warnings'] = 'Uyarıları Yönetiyor';
$l['changing_dst'] = '(DST) - Gün Işığı Zaman Ayarları Seçimini Değiştiriyor';
$l['printing_thread'] = 'Bir Konuyu Yazdırıyor';
$l['printing_thread2'] = '<a href="{1}">{2}</a> Konusunu Yazdırıyor';
$l['managing_buddyignorelist'] = 'Arkadaş &amp; Engelli Listesini Yönetiyor';
