<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Sat, 25 Apr 2020 03:22:11 +0000
// --------------------------------------------------------------------------------

$l['nav_portal'] = 'Portal';
$l['posted_by'] = 'Yazar:';
$l['forum'] = 'Forum:';
$l['replies'] = 'Yorum';
$l['no_replies'] = 'Yorum Yok';
$l['latest_threads'] = 'Son Yazılanlar';
$l['latest_threads_replies'] = 'Yorum';
$l['latest_threads_views'] = 'Okunma';
$l['latest_threads_lastpost'] = 'Son Yorum:';
$l['private_messages'] = 'Özel Mesajlar';
$l['pms_received_new'] = '{1}, Sitemize son ziyaretinizden bu yana<br /> Toplam: <strong>{2}</strong> tane yeni özel mesajınız bulunuyor.';
$l['pms_unread'] = 'Okunmamış Mesajlarınız';
$l['pms_total'] = 'Toplam Mesajlarınız';
$l['search_forums'] = 'Forumda Ara';
$l['advanced_search'] = 'Gelişmiş Arama';
$l['forum_stats'] = 'Forum İstatistikleri';
$l['num_members'] = 'Toplam Üyeler';
$l['latest_member'] = 'Son Üye';
$l['num_threads'] = 'Toplam Konular';
$l['num_posts'] = 'Toplam Yorumlar';
$l['full_stats'] = 'Detaylı İstatistikler';
$l['welcome'] = 'Hoşgeldin, {1}';
$l['guest_welcome_registration'] = 'Sitemizden yararlanabilmek için <a rel="nofollow" href="{1}" title="Üye Olmak İçin Tıklayın !" rel="tooltip">kayıt</a> olmalısınız.';
$l['username'] = 'Kullanıcı Adı';
$l['password'] = 'Şifreniz';
$l['login'] = 'Giriş Yap!';
$l['member_welcome_lastvisit'] = 'Son Ziyaretiniz:';
$l['since_then'] = '';
$l['new_announcements'] = '{1} Yeni Duyuru';
$l['new_announcement'] = '1 Yeni Duyuru';
$l['new_threads'] = '{1} Yeni Konu';
$l['new_thread'] = '1 Yeni Konu';
$l['new_posts'] = '{1} Yeni Yorum';
$l['new_post'] = '1 Yeni Yorum';
$l['view_new'] = 'Son Aktiviteler';
$l['view_todays'] = 'Bugünkü Yorumlar';
$l['online'] = 'Kimler Çevrimiçi';
$l['online_user'] = 'Şu anda 1 aktif kullanıcı var.';
$l['online_users'] = 'Şu anda {1} aktif kullanıcı var.';
$l['online_counts'] = '({1} Üye - {2} Ziyaretçi)';
$l['print_this_item'] = 'Bu konuyu yazdır';
$l['send_to_friend'] = 'Bu konuyu bir arkadaşına gönder';
$l['latest_announcements'] = 'Son Duyurular';
$l['portal_disabled'] = 'Portal işlevselliği forum yöneticisi tarafından kullanıma kapatılmıştır.';
