<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Tue, 19 May 2020 09:30:29 +0000
// --------------------------------------------------------------------------------

$l['nav_pms'] = 'Özel Mesajlar';
$l['nav_send'] = 'Yeni Mesaj Gönder';
$l['nav_tracking'] = 'Özel Mesaj Takibi';
$l['nav_folders'] = 'Klasör Yönetimi';
$l['nav_empty'] = 'Klasörleri Temizle';
$l['nav_export'] = 'Özel Mesajları Dışa Aktar/İndir';
$l['nav_search'] = 'Arama';
$l['nav_results'] = 'Arama Sonuçları';
$l['new_pm'] = '<i class="fas fa-envelope" style="color:#007fd0"></i>';
$l['old_pm'] = '';
$l['reply_pm'] = '<i class="fas fa-reply"></i>';
$l['fwd_pm'] = '<i class="fas fa-share"></i>';
$l['pms_disabled'] = 'Özel Mesaj Sistemi Forum Yönetimi Tarafından Kullanıma Kapatılmıştır.';
$l['private_messaging'] = 'Özel Mesajlar';
$l['inbox'] = 'Gelen Kutusu';
$l['compose_message2'] = 'Yeni Mesaj Gönder';
$l['manage_folders'] = 'Klasör Yönetimi';
$l['pm_search_results'] = 'Özel Mesaj Arama Sonuçları';
$l['message_title'] = 'Mesaj Başlığı';
$l['sender'] = 'Gönderen';
$l['sentto'] = 'Kime';
$l['date_sent'] = 'Gönderi Tarihi';
$l['desc'] = 'down';
$l['asc'] = 'up';
$l['delete_pm'] = 'Sil';
$l['move_to'] = 'Taşı';
$l['or'] = 'veya';
$l['selected_messages'] = 'Seçilen Mesajları';
$l['go'] = 'Git!';
$l['pmspaceused'] = 'Kullanılan Özel Mesaj Alanı';
$l['jump_folder'] = 'Klasör Seçimi:';
$l['archive_messages'] = 'Özel Mesajları Dışa Aktar/İndir';
$l['archive_note'] = 'Bu kısımdan, kullanıcı hesabınızda depolanan; okunmuş, okunmamış gelen/giden tüm özel mesajlarınızı aşağıdaki seçenekler yardımıyla kolay bir şekilde bilgisayarınıza indirebilirsiniz.';
$l['folders'] = 'Klasör Seçimi:';
$l['all_folders'] = 'Tüm Klasörler';
$l['date_limit'] = 'Tarihe Göre Seçim:';
$l['date_limit_older'] = 'Daha Eski Mesajlar';
$l['date_limit_newer'] = 'Daha Yeni Mesajlar';
$l['date_limit_disregard'] = 'Tarihi Yoksay';
$l['date_limit_days'] = 'Gün';
$l['export_unread'] = 'Okunmamış Mesajlar Aktarılsın mı?';
$l['delete_archived'] = 'Aktarılan Mesajlar Silinsin mi?';
$l['delete_archived_note'] = 'Aktarma/İndirme işleminden sonra özel mesajların klasörlerden silinmesini istiyorsanız <b>Evet</b> kutucuğunu işaretleyiniz.';
$l['export_format'] = 'Dosya Formatı Seçimi:';
$l['export_format_note'] = 'Bilgisayarınıza indirmek istediğiniz özel mesajların dosya formatını seçiniz.';
$l['export_html'] = 'HTML Dosyası (.html)';
$l['export_txt'] = 'Metin Belgesi (.txt)';
$l['export_csv'] = 'Microsoft Excel Dosyası (.csv)';
$l['private_messages_for'] = '{1} Adlı Kullanıcıya Ait Özel Mesajlar';
$l['exported_date'] = 'Aktarılma Tarihi: {1}, Saat: {2}';
$l['subject'] = 'Mesaj Başlığı:';
$l['to'] = 'Kime:';
$l['from'] = 'Gönderen:';
$l['sent'] = 'Gönderi Tarihi:';
$l['export_messages2'] = 'Mesajları İndir';
$l['empty_folders'] = 'Özel Mesaj Klasörlerini Temizle';
$l['empty_folders2'] = 'Klasörleri Temizle';
$l['empty_note'] = 'Bu kısımdan, kullanıcı hesabınızdaki Okunmuş, Okunmamış, Eski veya Yeni Tüm Özel Mesajlarınızı depolanan klasörlerden tek seferde silebilirsiniz.<br />Temizlemek istediğiniz klasörün sağ tarafında yer alan kutucuğu işaretleyip aşağıdaki Sil butonuna tıklayın.<br /><img src="images/icons/uyari.gif" style="vertical-align: middle;" alt="" height="14" width="14" /> <b>Uyarı:</b> Silinen mesajlar tekrar geri getirilemez. Silme işlemini gerçekleştirmeden önce lütfen, <a href="private.php?action=export">İndirme Yöneticisi</a> kısmından tüm Özel Mesajlarınızın yedeğini alın.';
$l['num_messages'] = 'Mesaj Sayısı:';
$l['empty_q'] = 'Silinsin mi?';
$l['keep_unread'] = 'Okunmamış Mesajlar Silinmesin? (seçiliyse silinmez)';
$l['pm_folders'] = 'Özel Mesaj Klasörleri';
$l['existing_folders'] = 'Mevcut Özel Mesaj Klasörleri:';
$l['edit_folder_note'] = 'Bu kısımdan, mevcut özel mesaj klasörlerinin isimlerini değiştirebilir, yeni bir klasör oluşturabilir ve oluşturduğunuz klasörleri silebilirsiniz. (Bazı klasörler silme işlemine kapalıdır.)<br /><img src="images/icons/uyari.gif" style="vertical-align: middle;" alt="" height="14" width="14" /> <b>Uyarı:</b> Herhangi bir klasörü sildiğinizde içindeki depolanmış tüm özel mesajlarda silinir.<br />Silmek için aşağıdaki metin kutularından silmek istediğiniz klasörün adını silip Klasörleri Güncelle butonuna tıklayın.<br />Silme işlemini gerçekleştirmeden önce lütfen <a href="private.php?action=export">İndirme Yöneticisi</a> kısmından tüm Özel Mesajlarınızın yedeğini alın.';
$l['new_folders'] = 'Yeni Bir Klasör Oluştur:';
$l['add_folders_note'] = 'Bu kısımdan yeni bir Özel Mesaj Klasörü oluşturabilirsiniz. Tüm metin kutularını doldurmanız gerekmez, her biri ayrı bir yeni klasör oluşturur.<br />Yeni bir klasör oluşturmak için aşağıdaki metin kutusuna klasör adını giriniz ve Klasörleri Güncelle butonuna tıklayın.';
$l['update_folders'] = 'Klasörleri Güncelle';
$l['cannot_be_removed'] = 'Değiştirilebilir/Silinemez';
$l['reached_warning'] = '<img src="images/icons/uyari.gif" style="vertical-align: middle;" alt="" height="14" width="14" /> <b>Uyarı:</b> Özel Mesaj Kotanız Dolmuştur.';
$l['reached_warning2'] = 'Özel mesaj kotanız dolmuştur. Yeni özel mesaj alabilmeniz için eski mesajlarınızı silmeniz gerekmektedir.';
$l['deny_receipt'] = '[Okunmadı Olarak İşaretle]';
$l['viewing_pm'] = 'ÖM Görüntüleme:';
$l['reply'] = 'Cevapla';
$l['reply_to_all'] = 'Tümünü Cevapla';
$l['forward'] = 'İlet';
$l['compose_pm'] = 'Yeni Özel Mesaj Gönder';
$l['compose_to'] = 'Kime:';
$l['compose_bcc'] = 'BCC:';
$l['compose_bcc_show'] = 'BCC';
$l['compose_bcc_show_title'] = 'BCC: Toplu ve Gizli Mail/ÖM gönderim kutusunu göster. Bu özellik Toplu Mail/ÖM gönderimi için Güvenli gönderim biçimidir.';
$l['separate_names'] = 'Birden fazla kullanıcıyı virgül ile ayırınız.';
$l['max_recipients'] = '<br />En fazla <b>{1}</b> kişiye mesaj gönderebilirsiniz.';
$l['compose_subject'] = 'Mesaj Başlığı:';
$l['compose_message'] = 'Mesaj İçeriği:';
$l['compose_options'] = 'Gönderim Seçenekleri:';
$l['message_icon'] = 'Başlık Sembolleri:';
$l['options_sig'] = 'İmzamı Göster';
$l['options_disable_smilies'] = 'İfadeleri Kapat';
$l['options_save_copy'] = 'Kopyasını Kaydet';
$l['options_read_receipt'] = 'Okundu Bildirimi Al';
$l['send_message'] = 'Mesajı Gönder';
$l['save_draft'] = 'Taslak Olarak Sakla';
$l['preview'] = 'Önizleme Yap';
$l['select_buddy'] = 'Bir Arkadaş Seçin:';
$l['pm_tracking'] = 'Özel Mesaj Takibi';
$l['read_messages'] = 'Okunmuş Mesajların Listesi';
$l['unread_messages'] = 'Okunmamış Mesajların Listesi';
$l['q'] = '?';
$l['dateread'] = 'Okunma Tarihi';
$l['stop_tracking'] = 'Mesaj Takibini Durdur';
$l['datesent'] = 'Gönderim Tarihi';
$l['cancel'] = 'İptal Et';
$l['export_date_sent'] = 'Tarih';
$l['export_folder'] = 'Klasör';
$l['export_subject'] = 'Konu';
$l['export_to'] = 'Kime';
$l['export_from'] = 'Gönderen';
$l['export_message'] = 'Mesaj';
$l['not_sent'] = '(Mesaj Yok)';
$l['at'] = '';
$l['nomessages'] = 'Bu klasörde henüz hiç özel mesaj bulunmamaktadır.';
$l['details'] = 'Ayrıntılar';
$l['message'] = 'Mesaj İçeriği';
$l['buddy_list'] = 'Arkadaş Listesi';
$l['multiple_recipients'] = '<em>Çoklu Alıcılar</em>';
$l['bcc'] = 'BCC:';
$l['reply_title'] = 'Bu Mesajı Cevapla';
$l['forward_title'] = 'Bu mesajı başka bir kullanıcıya gönder';
$l['delete_title'] = 'Bu Mesajı Sil';
$l['you_replied_on'] = '{1} bu mesajı cevapladınız';
$l['you_forwarded_on'] = '{1} bu mesajını gönderdiniz';
$l['you_replied'] = '{1} bu mesajı cevapladınız';
$l['you_forwarded'] = '{1} bu mesajını gönderdiniz';
$l['select_from_buddies'] = 'Arkadaşlarından Seç';
$l['no_readmessages'] = 'Henüz takipte olan okunmuş hiç mesajınız yok.';
$l['no_unreadmessages'] = 'Henüz takipte olan okunmamış hiç mesajınız yok.';
$l['stop_tracking_all'] = 'Tüm Mesaj Takiplerini Durdur.';
$l['enter_keywords'] = 'Aranacak kelime';
$l['advanced_search'] = 'Gelişmiş Arama';
$l['search_pms'] = 'ÖM Arama';
$l['advanced_private_message_search'] = 'Gelişmiş Özel Mesaj Araması';
$l['search_criteria'] = 'Arama Seçenekleri';
$l['keywords'] = 'Aranacak Kelime';
$l['search_in_subject'] = 'Başlığa Göre Ara';
$l['search_in_message'] = 'Mesaja Göre Ara';
$l['message_status'] = 'Mesaj Durumu';
$l['message_status_new'] = 'Yeni';
$l['message_status_replied_to'] = 'Cevaplanmış';
$l['message_status_forwarded'] = 'Gönderilmiş';
$l['message_status_read'] = 'Okunmuş';
$l['folder'] = 'Klasör';
$l['search_options'] = 'Diğer Seçenekler';
$l['sort_by'] = 'Listeleme Şekli';
$l['sort_by_subject'] = 'Başlık';
$l['sort_by_sender'] = 'Gönderen';
$l['sort_by_date'] = 'Tarih';
$l['ascending_order'] = 'Artan';
$l['descending_order'] = 'Azalan';
$l['search_private_messages'] = 'Aramayı Başlat';
$l['check_all'] = 'Tümünü Seç';
$l['error_nopmsarchive'] = 'Üzgünüz, fakat aradığınız kelimelere göre uygun hiçbir özel mesaj bulunamadı.';
$l['error_invalidpmfoldername'] = 'Üzgünüz, fakat girilen klasör adında izin verilmeyen karakterler mevcut.';
$l['error_emptypmfoldername'] = 'Üzgünüz, fakat girilen klasör adı hiçbir anlam içermiyor. Lütfen geçerli bir klasör adı giriniz veya metin kutusunu boş bırakarak geçersiz klasörün silinmesini sağlayabilirsiniz.';
$l['error_invalidpmrecipient'] = "Geçersiz veya mevcut olmayan bir kullanıcı/alıcı adı girdiniz. Lütfen geri dönüp geçerli bir kullanıcı/alıcı adı giriniz.";
$l['error_invalidmovefid'] = "Mesaj(lar)ınızı taşımaya çalıştığınız klasör geçersiz. Lütfen geri dönün ve tekrar deneyin.";
$l['error_invalidpm'] = 'Geçersiz Özel Mesaj';
$l['error_pmrecipientreachedquota'] = '{1} adlı kullanıcıya özel mesaj gönderemezsiniz. Çünkü, {1} adlı kullanıcının özel mesaj kotası dolmuştur. Bu durum hakkında {1} adlı kullanıcıya e-posta bildirimi gönderilmiştir. Lütfen daha sonra tekrar deneyiniz.';
$l['error_recipientpmturnedoff'] = '{1} adlı kullanıcı özel mesaj alımını kapatmış veya yönetim {1} adlı kullanıcının özel mesaj kullanımını engellemiş olabilir. Bu sebepten dolayı {1} adlı kullanıcıya özel mesaj gönderilemiyor.';
$l['error_pmsturnedoff'] = 'Profil ayarlarınızdan özel mesaj sistemini devre dışı bırakmışsınız.<br />Diğer kullanıcılardan özel mesaj alabilmek ve özel mesaj sistemini kullanabilmeniz için profil ayarlarınızdan tekrar aktif etmeniz gerekiyor.';
$l['error_recipientignoring'] = '{1} adlı kullanıcıya özel mesaj gönderemezsiniz. Çünkü bunu yapmaya izniniz yok.';
$l['error_pm_already_submitted'] = 'Son 5 saat içinde aynı mesajı aynı kişiye zaten göndermişsiniz.';
$l['error_nopms'] = 'Bu fonksiyonun erişilebilir olması için bir veya daha fazla özel mesaj olmalıdır.';
$l['error_minsearchlength'] = 'Bir veya daha fazla arama teriminiz minimum uzunluktan fazla. Arama karakter sayısı en az {1} olmalı.';
$l['error_nosearchresults'] = 'Üzgünüz, fakat belirtmiş olduğunuz kriterlere uygun hiçbir sonuç bulunamadı. Lütfen farklı bir arama terimi ile tekrar deneyin.';
$l['error_no_search_support'] = 'Veritabanı sistemi bu arama sorgusunu desteklemiyor.';
$l['error_nosearchterms'] = 'Belirtmiş olduğunuz arama terimine izin verilmedi. Arama yapmak için herhangi bir kelime girmediniz. Lütfen bir kelime veya kullanıcı adı girip tekrar deneyin.';
$l['error_searchflooding_1'] = 'Üzgünüz, fakat her {1} saniyede bir arama yapabilirsiniz. Lütfen arama yapabilmek için 1 saniye daha bekleyin ve tekrar deneyin.';
$l['error_searchflooding'] = 'Üzgünüz, kakat her {1} saniyede bir arama yapabilirsiniz. Lütfen arama yapabilmek için {2} saniye daha bekleyin ve tekrar deneyin.';
$l['error_invalidsearch'] = 'Geçersiz arama. Lütfen geri dönüp tekrar deneyin.';
$l['redirect_pmsaved'] = 'Özel mesajınız taslaklar klasörünüze kaydedilmiştir.';
$l['redirect_pmstrackingstopped'] = 'Seçmiş olduğunuz özel mesajların takibi durdulmuştur.';
$l['redirect_pmstrackingcanceled'] = 'Seçmiş olduğunuz özel mesajlar alıcının gelen kutusundan silinmiştir.';
$l['redirect_allpmstrackingstopped'] = 'Tüm mesaj takipleri durduruldu.';
$l['redirect_pmsmoved'] = 'Seçmiş olduğunuz özel mesajlar taşınmıştır.';
$l['redirect_pmsdeleted'] = 'Seçmiş olduğunuz özel mesajlar silinmiştir.<br />Şimdi gelen kutusuna geri yönlendiriliyorsunuz...';
$l['redirect_pmsent'] = 'Teşekkürler, özel mesajınız alıcıya başarıyla gönderildi.<br />Şimdi gelen kutusuna geri yönlendiriliyorsunuz...';
$l['redirect_pmfoldersupdated'] = 'Teşekkürler, özel mesaj klasörünüz başarıyla güncellendi.<br />Şimdi gelen kutusuna geri yönlendiriliyorsunuz...';
$l['redirect_pmfoldersemptied'] = 'Seçmiş olduğunuz özel mesaj klasörleri başarıyla temizlendi.<br />Şimdi gelen kutusuna geri yönlendiriliyorsunuz...';
$l['redirect_searchresults'] = 'Teşekkürler, arama teriminiz başarıyla işleme alındı.<br />Şimdi arama sonuçları listesine yönlendiriliyorsunuz...';
$l['quick_reply'] = 'Hızlı Cevap';
$l['message_note'] = 'Bu mesaj için cevap yazınız.';
$l['send_reply'] = 'Cevabı Gönder';
$l['quickreply_signature'] = 'İmzamı Göster';
$l['quickreply_disable_smilies'] = 'İfadeleri Kapat';
$l['quickreply_save_copy'] = 'Kopyasını Kaydet';
$l['quickreply_read_receipt'] = 'Okundu Bildirimi Al';
