<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Tue, 28 Apr 2020 02:18:52 +0000
// --------------------------------------------------------------------------------

$l['nav_reputation'] = 'Teşekkür Puanı Raporu';
$l['nav_profile'] = '{1}, İsimli Kullanıcının Profili';
$l['reputation_disabled'] = 'Teşekkür puanı sistemi, forum yönetimi tarafından kullanıma kapatılmıştır.';
$l['reputation'] = 'Teşekkür Puanı';
$l['error'] = 'Hata';
$l['add_no_uid'] = 'Teşekkür puanı vermek için herhangi bir kullanıcı seçmediniz.';
$l['add_no_permission'] = 'Kullanıcılara teşekkür puanı verme yetkiniz yok.';
$l['add_disabled'] = 'Bu kullanıcı grubundaki kullanıcılara teşekkür puanı veremezsiniz.';
$l['add_yours'] = 'Kendi kendinize teşekkür puanı veremezsiniz.';
$l['add_invalidpower'] = 'Bu listeden geçersiz bir puan seçtiniz.';
$l['add_maxperday'] = 'Bugün için izin verilenden fazla teşekkür puanı verdiniz.';
$l['add_maxperuser'] = 'Zaten bu kullanıcıya bugün için çok fazla puan vermişsiniz.';
$l['add_maxperthread'] = 'Bu konu hakkında, bu kullanıcıya, bu gün için zaten çok fazla puan vermişsiniz.';
$l['add_no_comment'] = 'Bu kullanıcıya teşekkür puanı verebilmeniz için en az 10 karakterlik bir yorum yazmanız gerekiyor.';
$l['add_toolong'] = 'En az {1} karakterlik bir yorum, (sebep) yazmalısınız.';
$l['add_negative_disabled'] = 'Negatif teşekkür puanı kullanımı, yönetim tarafından engellenmiştir.';
$l['add_neutral_disabled'] = 'Tarafsız teşekkür puanı kullanımı, yönetim tarafından engellenmiştir.';
$l['add_positive_disabled'] = 'Pozitif teşekkür puanı kullanımı, yönetim tarafından engellenmiştir.';
$l['add_all_rep_disabled'] = 'Teşekkür puanı sistemi, genel olarak yönetim tarafından kullanıma kapatılmıştır.';
$l['reputation_report'] = '{1} - Teşekkür Puanı Tablosu';
$l['reputation_members'] = 'Teşekkür Eden Kullanıcı Sayısı';
$l['reputation_posts'] = 'Teşekkür Edilen Konu &amp; Yorum Sayısı';
$l['summary'] = 'Teşekkür Puanı Bilgileri';
$l['total_reputation'] = 'Toplam Teşekkür Puanı';
$l['post_reputation'] = 'Konu &amp; Yorum Puanı';
$l['positive_count'] = '<img src="images/icons/pozitif.png" alt="pozitif" style="vertical-align: middle;" height="12" width="12" />&nbsp;Pozitif';
$l['neutral_count'] = '<img src="images/icons/tarafsiz.png" alt="tarafsız" style="vertical-align: middle;" height="12" width="12" />&nbsp;Tarafsız';
$l['negative_count'] = '<img src="images/icons/negatif.png" alt="negatif" style="vertical-align: middle;" height="12" width="12" />&nbsp;Negatif';
$l['last_week'] = 'Geçen Hafta:';
$l['last_month'] = 'Geçen Ay:';
$l['last_6months'] = 'Son 6 Ay:';
$l['all_time'] = 'Tüm Zamanlar:';
$l['comments'] = 'Teşekkür Puanı Yorumları';
$l['close_window'] = 'Pencereyi Kapat';
$l['add_reputation_vote'] = '{1}, isimli kullanıcıya teşekkür et !';
$l['add_reputation_to_post'] = '{1}, isimli kullanıcıya bu konu için teşekkür et !<br />';
$l['neg_rep_disabled'] = ' <span class="smalltext"><em>(- Teşekkür puanı kullanımı, şu anda devre dışı)</em></span>';
$l['pos_rep_disabled'] = ' <span class="smalltext"><em>(+ Teşekkür puanı kullanımı, şu anda devre dışı)</em></span>';
$l['neu_rep_disabled'] = ' <span class="smalltext"><em>(Tarafsız teşekkür puanı kullanımı, şu anda devre dışı)</em></span>';
$l['no_comment_needed'] = 'Aşağıdaki Metin Kutusuna Teşekkür Puanı İçin Yorumunuzu Yazınız.<br />';
$l['no_comment'] = '[Yorum Yok]';
$l['vote_added'] = 'Puan Eklendi';
$l['vote_updated'] = 'Puan Güncellendi';
$l['vote_deleted'] = 'Puan Silindi';
$l['vote_added_message'] = 'Bu Kullanıcıya Başarılı Olarak Teşekkür Puanı Verildi.';
$l['vote_updated_message'] = 'Bu Kullanıcıya Vermiş Olduğunuz Teşekkür Puanı Başarılı Olarak Güncellendi.';
$l['vote_deleted_message'] = 'Bu Kullanıcıya Vermiş Olduğunuz Teşekkür Puanı Başarılı Olarak Silindi.';
$l['update_reputation_vote'] = '{1} İsimli Kullanıcının Teşekkür Puanını Güncelle.';
$l['positive'] = 'Pozitif';
$l['negative'] = 'Negatif';
$l['neutral'] = 'Tarafsız';
$l['user_comments'] = '{1}, isimli kullanıcı için teşekkür puanı yorumunuz:';
$l['add_vote'] = 'Teşekkür Puanı Ekle';
$l['update_vote'] = 'Teşekkür Puanı Güncelle';
$l['delete_vote'] = 'Sil';
$l['report_vote'] = 'Rapor Et';
$l['power_positive'] = 'Pozitif ({1})';
$l['power_neutral'] = 'Tarafsız';
$l['power_negative'] = 'Negatif ({1})';
$l['show_all'] = 'Tüm Oyları Göster';
$l['show_positive'] = 'Pozitif Oyları Göster';
$l['show_neutral'] = 'Tarafsız Oyları Göster';
$l['show_negative'] = 'Negatif Oyları Göster';
$l['sort_updated'] = 'Son Güncelleştirmeye Göre Listele';
$l['sort_username'] = 'Kulanıcı Adına Göre Listele';
$l['last_updated'] = 'Son Güncelleme Tarihi: {1}';
$l['postrep_given'] = '<strong>{2}</strong> için <a href="{1}">teşekkür edilen mesaj</a>&nbsp;<img src="images/icons/external_link.png" alt="" style="vertical-align: middle;" height="9" width="9" />, {3}&nbsp;<img src="images/icons/external_link.png" alt="" style="vertical-align: middle;" height="9" width="9" /><br />';
$l['postrep_given_nolink'] = 'Teşekkür edilen mesaj: {1}<br />';
$l['postrep_given_thread'] = 'Konu: <a href="{1}">{2}</a>';
$l['no_reputation_votes'] = 'Bu kullanıcıya henüz teşekkür puanı yorumu yazılmamış. Bunun sebebi aşağıdakilerden biri olabilir:<br /><strong>1.</strong> Bu kullanıcıya henüz hiç teşekkür puanı verilmemiştir.<br /><strong>2.</strong> Bu kullanıcıya verilen teşekkür puanları için yorum yazılmamış olabilir.';
$l['delete_reputation_confirm'] = 'Teşekkür Puanını Silmek İstediğinizden Emin misiniz?';
$l['delete_reputation_log'] = '{1} isimli kullanıcının, vermiş olduğu teşekkür puanı sildi.';
$l['reputations_disabled_group'] = 'Bu kullanıcı grubu için Teşekkür Puanı Sistemi devre dışı bırakılmıştır.';
$l['rate_user'] = 'Teşekkür Et !';
