<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Thu, 14 May 2020 01:18:29 +0000
// --------------------------------------------------------------------------------

$l['nav_search'] = 'Arama Sayfası';
$l['nav_results'] = 'Arama Sonuçları';
$l['pages'] = "Sayfalar:";
$l['pages_last'] = 'Son';
$l['search'] = 'Arama Yap';
$l['search_keyword'] = 'Kelime Ara';
$l['search_username'] = 'Kullanıcı Adına Göre Ara';
$l['search_entire_post'] = 'Konu İçinde Ara';
$l['search_titles_only'] = 'Konu Başlığında Ara';
$l['match_username'] = 'Kullanıcı Adını Tam Eşleştir';
$l['search_forums'] = 'Forumlarda Ara';
$l['search_all_forums'] = 'Tüm Açık Forumları Ara';
$l['search_options'] = 'Arama Seçenekleri';
$l['threads_at_least'] = 'En Az Yorumlanan Konuları Bul';
$l['threads_at_most'] = 'En Çok Yorumlanan Konuları Bul';
$l['find_anydate'] = 'Tüm Yorumları Ara';
$l['find_yesterday'] = 'Dünkü Yorumları Ara';
$l['find_lastweek'] = 'Geçen Haftaki Yorumları Ara';
$l['find_2weeks'] = '2 Hafta Önceki Yorumları Ara';
$l['find_month'] = '1 Ay Önceki Yorumları Ara';
$l['find_3months'] = '3 Ay Önceki Yorumları Ara';
$l['find_6months'] = '6 Ay Önceki Yorumları Ara';
$l['find_year'] = '1 Yıl Önceki Yorumları Ara';
$l['and_newer'] = 'Önce Yeniler';
$l['and_older'] = 'Önce Eskiler';
$l['sorting_options'] = 'Listeleme Seçenekleri:';
$l['sort_lastpost'] = 'Son Gönderime Göre Listele';
$l['sort_author'] = 'Yazara Göre Listele';
$l['sort_forum'] = 'Foruma Göre Listele';
$l['sort_in'] = '';
$l['sort_asc'] = 'Artan';
$l['sort_desc'] = 'Azalan';
$l['sort_order'] = 'Sıralama';
$l['asc'] = 'up';
$l['desc'] = 'down';
$l['display_options'] = 'Görüntüleme Seçenekleri';
$l['show_results_as'] = 'Neye Göre Listelensin?';
$l['show_results_threads'] = 'Konulara Göre';
$l['show_results_posts'] = 'Yorumlara Göre';
$l['search_results'] = 'Arama Sonuçları';
$l['post'] = 'Yorum';
$l['author'] = 'Konuyu Başlatan';
$l['forum'] = 'Forum';
$l['replies'] = 'Yorumlar';
$l['views'] = 'Okunma';
$l['posted'] = 'Yayınlanan';
$l['thread'] = 'Konu';
$l['lastpost'] = 'Son Yorum';
$l['post_thread'] = 'Konu:';
$l['post_subject'] = 'Yorum:';
$l['replies2'] = 'Yorum Sayısı';
$l['selectall'] = 'Ek Sonuçların Tümü Seçilsin mi?';
$l['any_prefix'] = 'Rastgele Bir Kelimeye Göre Ara';
$l['no_prefix'] = 'Ön Ek Yok';
$l['inline_thread_moderation'] = 'Konu Yönetim Araçları:';
$l['close_threads'] = 'Konuyu Kapat';
$l['open_threads'] = 'Konuyu Aç';
$l['stick_threads'] = 'Konuyu Üstte Tuttur';
$l['unstick_threads'] = 'Konuyu Üstten Kaldır';
$l['soft_delete_threads'] = 'Konuyu Gizle/Geçici Sil';
$l['restore_threads'] = 'Konuyu Onar/Geri Getir';
$l['delete_threads'] = 'Konuyu Sil';
$l['move_threads'] = 'Konuyu Taşı/Kopyala';
$l['approve_threads'] = 'Konuyu Onayla';
$l['unapprove_threads'] = 'Konu Onayını Kaldır';
$l['inline_soft_delete_posts'] = 'Yorumları Gizle/Geçici Sil';
$l['inline_restore_posts'] = 'Yorumları Onar/Geri Getir';
$l['inline_delete_posts'] = 'Yorumları Sil';
$l['inline_merge_posts'] = 'Yorumları Birleştir';
$l['inline_split_posts'] = 'Yorumları Ayrıştır';
$l['inline_move_posts'] = 'Yorumları Taşı';
$l['inline_approve_posts'] = 'Yorumları Onayla';
$l['inline_unapprove_posts'] = 'Yorumların Onayını Kaldır';
$l['inline_post_moderation'] = 'Satır İçi Konu Yönetimi:';
$l['inline_go'] = 'Git';
$l['clear'] = 'İptal Et';
$l['icon_dot'] = 'Sizin Yorumunuzu İçerir. ';
$l['icon_no_new'] = 'Yeni Yorum Yok. ';
$l['icon_new'] = 'Yeni Yorum. ';
$l['icon_hot'] = 'Sıcak Konu. ';
$l['icon_close'] = 'Konu Kapalı.';
$l['attachment_count'] = 'Bu Konu 1 Ek İçeriyor.';
$l['attachment_count_multiple'] = 'Bu Konu {1} Ek İçeriyor.';
$l['goto_first_unread'] = 'Okunmamış ilk mesaja git';
$l['page_selected'] = 'Bu Sayfadaki Tüm <strong>{1}</strong> Sonuçları Seç.';
$l['all_selected'] = 'Bu Sayfadaki Tüm <strong>{1}</strong> Arama Sonuçlarını Seç';
$l['select_all'] = 'Bu Aramadaki Tüm <strong>{1}</strong> Sonuçları Seç';
$l['clear_selection'] = 'Seçimi İptal Et';
$l['results'] = '';
$l['mod_options'] = 'Moderatör Seçenekleri';
$l['display_all'] = 'Tümünü Ara';
$l['display_only_approved'] = 'Sadece Onaylanmışları Ara';
$l['display_only_unapproved'] = 'Sadece Onaylanmamışları Ara';
$l['display_only_softdeleted'] = 'Sadece Gizlenmiş/Geçici Silinmişleri Ara';
$l['redirect_searchresults'] = 'Teşekkürler, aramanız işleme alınmıştır. Şimdi arama sonuçları sayfasına geri yönlendiriliyorsunuz...';
$l['error_minsearchlength'] = 'Aramak istediğiniz kelime en az {1} karakter uzunluğunda olmalıdır.';
$l['error_nosearchresults'] = 'Üzgünüz, fakat aradığınız kelime ile ilgili herhangi bir sonuç bulunamadı. Lütfen geri dönüp farklı bir arama terimi deneyin.';
$l['error_no_search_support'] = 'Veritabanı sistemi bu arama sorgusunu desteklemiyor.';
$l['error_nosearchterms'] = 'Arama yapmak için herhangi bir kelime girmediniz. Lütfen bir Kelime yada Kullanıcı Adı girip tekrar deneyin.';
$l['error_searchflooding_1'] = 'Üzgünüz, fakat her {1} saniyede bir arama yapabilirsiniz. Lütfen arama yapabilmek için 1 saniye daha bekleyin ve tekrar deneyin.';
$l['error_searchflooding'] = 'Üzgünüz, fakat her {1} saniyede bir arama yapabilirsiniz. Lütfen arama yapabilmek için {2} saniye daha bekleyin ve tekrar deneyin.';
$l['error_invalidsearch'] = 'Geçersiz Arama. Lütfen geri dönüp tekrar deneyin.';
