<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Fri, 22 May 2020 21:22:27 +0000
// --------------------------------------------------------------------------------

$l['nav_showteam'] = 'Forum Yöneticileri';
$l['forum_team'] = 'Forum Yöneticileri';
$l['moderators'] = 'Yöneticiler';
$l['username'] = 'Kullanıcı Adı';
$l['lastvisit'] = 'Son Ziyareti';
$l['email'] = 'E-Posta';
$l['pm'] = 'ÖM';
$l['mod_forums'] = 'Sorumlu Olduğu Forum(lar)';
$l['mod_groups'] = 'Sorumlu Olduğu Grup(lar)';
$l['online'] = 'online';
$l['offline'] = 'offline';
$l['away'] = 'away';
$l['group_leaders'] = 'Grup Liderleri';
$l['group_members'] = 'Üyeler';
$l['no_members'] = 'Bu grupta henüz hiç üye yok.';
$l['showteam_disabled'] = 'Forum yöneticilerini görüntüleme özelliği site yönetimi tarafından devre dışı bırakıldı.';
$l['error_noteamstoshow'] = 'Şu anda gösterilecek herhangi bir yönetici mevcut değil.';
