<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Mon, 04 May 2020 23:47:49 +0000
// --------------------------------------------------------------------------------

$l['nav_stats'] = 'Forum İstatistikleri';
$l['stats_disabled'] = 'Forum istatistikleri sayfası yönetici tarafından gösterime kapatılmıştır.';
$l['board_stats'] = 'Genel Forum İstatistikleri';
$l['none'] = 'Yok';
$l['totals'] = 'Toplam';
$l['averages'] = 'Ortalama Değerler';
$l['posts'] = 'Yorumlar';
$l['threads'] = 'Konular';
$l['members'] = 'Üye Sayısı';
$l['ppd'] = 'Ortalama günlük yazılan yorumlar';
$l['tpd'] = 'Ortalama günlük açılan konular';
$l['mpd'] = 'Ortalama günlük üye kayıtları';
$l['ppm'] = 'Ortalama üye başına yazılan yorumlar';
$l['tpm'] = 'Ortalama üye başına açılan konular';
$l['rpt'] = 'Ortalama konu başına yazılan yorumlar';
$l['no_posts'] = 'Yorum Yok';
$l['general'] = 'Genel İstatistik';
$l['newest_member'] = 'En son kayıt olan üye';
$l['members_posted'] = 'Yorum yazan kullanıcılar ortalama';
$l['todays_top_poster'] = 'Bugün en çok yorum yazan: {1} ({2} yorum)';
$l['popular_forum'] = 'En popüler forum: {1} ({2} yorum, {3} konu)';
$l['most_popular'] = 'En Popüler &amp; Güncel Konular Listesi';
$l['most_replied_threads'] = 'En Çok Yorumlanan Konular';
$l['most_viewed_threads'] = 'En Çok Okunan Konular';
$l['not_enough_info_stats'] = 'Üzgünüz: Henüz gösterilecek herhangi bir istatistik oluşmamış. Forum istatistik tablosunun oluşması için en az 1 üye, 1 konu ve 1 yorum olması gerekiyor.';
$l['replies'] = 'yorum';
$l['views'] = 'okunma';
$l['top_referrer'] = 'En çok referansı olan kullanıcı: {1} ({2} referans)';
