<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Tue, 21 Apr 2020 14:19:37 +0000
// --------------------------------------------------------------------------------

$l['ucp_nav_width'] = '185';
$l['ucp_nav_menu'] = 'Kontrol Panel Araçları';
$l['ucp_nav_messenger'] = 'Özel Mesaj Yönetimi';
$l['ucp_nav_compose'] = 'Yeni Mesaj Gönder';
$l['ucp_nav_tracking'] = 'Özel Mesaj Takibi';
$l['ucp_nav_edit_folders'] = 'Klasör Yönetimi';
$l['ucp_nav_profile'] = 'Hesap Yönetimi';
$l['ucp_nav_edit_profile'] = 'Profili Düzenle';
$l['ucp_nav_edit_options'] = 'Hesap Seçenekleri';
$l['ucp_nav_change_email'] = 'E-Postanı Değiştir';
$l['ucp_nav_change_pass'] = 'Şifreni Değiştir';
$l['ucp_nav_change_username'] = 'Kullanıcı Adını Değiştir';
$l['ucp_nav_edit_sig'] = 'İmzanı Değiştir';
$l['ucp_nav_change_avatar'] = 'Avatarını Değiştir';
$l['ucp_nav_misc'] = 'Diğer Araçlar';
$l['ucp_nav_editlists'] = 'Arkadaş/Engelli';
$l['ucp_nav_favorite_threads'] = 'Favori Konular';
$l['ucp_nav_subscribed_threads'] = 'Takip Edilen Konu';
$l['ucp_nav_forum_subscriptions'] = 'TakipEdilen Forum';
$l['ucp_nav_drafts'] = 'Kayıtlı Taslaklar';
$l['ucp_nav_drafts_active'] = 'Kayıtlı Taslaklarım: {1}';
$l['ucp_nav_notepad'] = 'Kişisel Notlarım';
$l['ucp_nav_view_profile'] = 'Profilini Gör';
$l['ucp_nav_home'] = 'Kullanıcı KP';
$l['ucp_nav_usergroups'] = 'Grup Üyelikleri';
$l['ucp_nav_attachments'] = 'Ek Dosya Yönetimi';
